Repository stoneatom/stonedb, pull requests merged in 2022-11, with the labels that each got.

#858 feat(tianmu): Improve the tianmu code (#11)
  storage/tianmu/base/core/reactor.cpp
  storage/tianmu/core/aggregation_algorithm.cpp
  storage/tianmu/core/aggregation_algorithm.h
  storage/tianmu/core/engine_results.cpp
  storage/tianmu/core/groupby_wrapper.cpp
  storage/tianmu/core/temp_table.cpp
  storage/tianmu/core/temp_table.h
  storage/tianmu/core/temp_table_com.cpp
  storage/tianmu/core/temp_table_low.cpp
  storage/tianmu/core/temp_table_roughquery.cpp
  storage/tianmu/vc/subselect_column.cpp
Labels: PR-feature

#862 test(mtr): add derived_table.test and create_drop_users.test(#497)
  mysql-test/suite/tianmu/r/create_drop_users.result
  mysql-test/suite/tianmu/r/derived_table.result
  mysql-test/suite/tianmu/t/create_drop_users.test
  mysql-test/suite/tianmu/t/derived_table.test
Labels: PR-testing

#859 feat(tianmu): fix up the compile warnings on CentOS. (#844)
  cmake/maintainer.cmake
  storage/tianmu/CMakeLists.txt
  storage/tianmu/base/core/future.h
  storage/tianmu/base/core/posix.h
  storage/tianmu/base/core/reactor.cpp
  storage/tianmu/base/core/systemwide_memory_barrier.cpp
  storage/tianmu/core/temp_table_low.cpp
  storage/tianmu/core/transaction.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
Labels: PR-feature

#871 test(mtr): add insert_select_from.test and show_db_table.test(#497)
  mysql-test/suite/tianmu/r/insert_select_from.result
  mysql-test/suite/tianmu/r/show_db_table.result
  mysql-test/suite/tianmu/t/insert_select_from.test
  mysql-test/suite/tianmu/t/show_db_table.test
Labels: PR-testing

#869 fix(tianmu): fix duplicate 'lc-messages-dir' config item in my.cnf.sample file. (#688)
  scripts/my.cnf.sample
Labels: PR-bug

#868 fix(StoneDB 8.0): fix duplicate 'lc-messages-dir' config item in my.cnf.sample file. (#688)
  scripts/my.cnf.sample
Labels: PR-bug

#875 feat(tianmu): Improve the readbility of stonedb. (#11)
  storage/tianmu/exporter/data_exporter.cpp
  storage/tianmu/exporter/data_exporter.h
  storage/tianmu/exporter/data_exporter_txt.cpp
  storage/tianmu/exporter/data_exporter_txt.h
  storage/tianmu/exporter/export2file.cpp
  storage/tianmu/exporter/export2file.h
  storage/tianmu/loader/load_parser.cpp
  storage/tianmu/loader/load_parser.h
  storage/tianmu/loader/parsing_strategy.cpp
  storage/tianmu/loader/parsing_strategy.h
Labels: PR-feature

#866 feat(tianmu 8.0):Improve the readbility of stonedb. (#11)
  storage/tianmu/exporter/data_exporter.cpp
  storage/tianmu/exporter/data_exporter.h
  storage/tianmu/exporter/data_exporter_txt.cpp
  storage/tianmu/exporter/data_exporter_txt.h
  storage/tianmu/exporter/export2file.cpp
  storage/tianmu/exporter/export2file.h
  storage/tianmu/loader/load_parser.cpp
  storage/tianmu/loader/load_parser.h
  storage/tianmu/loader/parsing_strategy.cpp
  storage/tianmu/loader/parsing_strategy.h
Labels: PR-feature

#876 feat(tianmu): Improve the readbility of stonedb. (#11)
  storage/tianmu/common/common_definitions.h
  storage/tianmu/common/data_format.cpp
  storage/tianmu/common/data_format.h
  storage/tianmu/common/exception.h
  storage/tianmu/common/sequence_generator.h
Labels: PR-feature

#877 fix(tianmu): fix problems related to master slave synchronization (#819)
  mysql-test/suite/tianmu/r/issue819.result
  mysql-test/suite/tianmu/t/issue819.test
  sql/log_event.cc
  sql/sql_insert.cc
  sql/sql_optimizer.cc
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-bug

#865 feat(tianmu): support 'ALTER TABLE t1 CHARACTER SET = ...' clause. (#848)
  mysql-test/suite/tianmu/r/issue848.result
  mysql-test/suite/tianmu/t/issue848.test
  storage/tianmu/handler/tianmu_handler.cpp
  storage/tianmu/handler/tianmu_handler.h
Labels: PR-feature

#882 feat(tianmu): Improve code readability (#11)
  storage/tianmu/core/engine.ic
  storage/tianmu/core/temp_table_roughquery.cpp
Labels: PR-feature

#883 feat(tianmu): fix stonedb version number in README
  INSTALL
  README
Labels: PR-feature

#878 feat(tianmu): support alter table xxx modify xxx type NULL/NOT NULL(#860)
  mysql-test/suite/tianmu/r/alter_table_null.result
  mysql-test/suite/tianmu/t/alter_table_null.test
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-feature, C-stonedb-5.7

#891 feat(handler): refactor code in handler module #890
  sql/sql_load.cc
  sql/sql_parse.cc
  sql/sql_show.cc
  storage/tianmu/core/compilation_tools.cpp
  storage/tianmu/core/compilation_tools.h
  storage/tianmu/core/engine.h
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/query.cpp
  storage/tianmu/core/query.h
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/handler/ha_my_tianmu.h
  storage/tianmu/handler/ha_rcengine.cpp
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-feature

#894 fix(tianmu): revert some refactor code issue. (#11)
  storage/tianmu/compress/code_stream.h
  storage/tianmu/compress/data_stream.h
  storage/tianmu/compress/ppm_defs.h
  storage/tianmu/compress/suffix_tree.cpp
  storage/tianmu/compress/suffix_tree.h
  storage/tianmu/compress/word_graph.cpp
  storage/tianmu/compress/word_graph.h
  storage/tianmu/types/rc_item_types.h
  storage/tianmu/types/rc_num.cpp
  storage/tianmu/types/text_stat.cpp
  storage/tianmu/types/text_stat.h
Labels: PR-bug

#903 test(mtr): add some mtr testcases(#497)
  mysql-test/suite/tianmu/r/cast_json_func.result
  mysql-test/suite/tianmu/r/inner_join.result
  mysql-test/suite/tianmu/r/left_join.result
  mysql-test/suite/tianmu/r/period_diff.result
  mysql-test/suite/tianmu/r/select_from.result
  mysql-test/suite/tianmu/r/strings.result
  mysql-test/suite/tianmu/r/various_subquery.result
  mysql-test/suite/tianmu/t/cast_json_func.test
  mysql-test/suite/tianmu/t/inner_join.test
  mysql-test/suite/tianmu/t/left_join.test
  mysql-test/suite/tianmu/t/period_diff.test
  mysql-test/suite/tianmu/t/select_from.test
  mysql-test/suite/tianmu/t/strings.test
  mysql-test/suite/tianmu/t/various_subquery.test
Labels: PR-testing

#896 fix(tianmu): revert some refactor code issue. (#11)
  storage/tianmu/compress/code_stream.h
  storage/tianmu/compress/data_stream.h
  storage/tianmu/compress/ppm_defs.h
  storage/tianmu/compress/suffix_tree.cpp
  storage/tianmu/compress/suffix_tree.h
  storage/tianmu/compress/word_graph.cpp
  storage/tianmu/compress/word_graph.h
  storage/tianmu/types/rc_item_types.h
  storage/tianmu/types/rc_num.cpp
  storage/tianmu/types/text_stat.cpp
  storage/tianmu/types/text_stat.h
Labels: PR-bug

#904 feat(tianmu): fix invalid write/read issue. (#817)
  storage/tianmu/system/cacheable_item.cpp
  storage/tianmu/system/cacheable_item.h
Labels: PR-feature

#902 feat(tianmu): fix invalid write/read issue. (#817)
  storage/tianmu/core/engine_results.cpp
  storage/tianmu/system/cacheable_item.cpp
  storage/tianmu/system/cacheable_item.h
Labels: PR-feature

#924 docs(troubleshooting): Deleting Invalid Documents(#923)
  Docs/08-troubleshooting/failed-to-operate-table.md
  Docs/download.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/08-troubleshooting/failed-to-operate-table.md
Labels: PR-docs

#918 feat(tianmu): every file has no such file or directory warning.(#916)
  storage/tianmu/CMakeLists.txt
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/types/rc_item_types.h
Labels: PR-feature

#926 test(mtr): add alter_table_v1.result(#497)
  mysql-test/suite/tianmu/r/alter_table_v1.result
Labels: PR-testing

#911 feat(handler): change the default tianmu log path from $mysqlhome/log/ to $mysqlhome/data/ #609
  storage/tianmu/handler/tianmu_handler_com.cpp
Labels: PR-feature

#917 feat(handler): change the default tianmu log path to $mysqlhome/data #609
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#931 fix(tianmu): fix crashed when the subquery includes a SORT clause (#906)
  mysql-test/suite/tianmu/r/issue906.result
  mysql-test/suite/tianmu/t/issue906.test
  storage/tianmu/core/temp_table.h
  storage/tianmu/vc/subselect_column.cpp
Labels: PR-bug

#941 feat(tianmu): refactor tianm and fix warnings(#11)
  storage/tianmu/core/mi_iterator.cpp
  storage/tianmu/core/mi_new_contents.cpp
  storage/tianmu/core/multi_index.cpp
  storage/tianmu/core/multi_index.h
  storage/tianmu/core/multi_index_builder.cpp
  storage/tianmu/system/cacheable_item.cpp
Labels: PR-feature

#945 feat(tianmu): fix stonedb5.7 warnings. (#11)
  storage/tianmu/async_tests/task_executor.h
  storage/tianmu/base/core/iostream_impl.h
  storage/tianmu/common/exception.h
  storage/tianmu/compress/part_dict.cpp
  storage/tianmu/compress/text_compressor.cpp
  storage/tianmu/core/aggregation_algorithm.cpp
  storage/tianmu/core/column.h
  storage/tianmu/core/item_tianmu_field.cpp
  storage/tianmu/core/joiner.cpp
  storage/tianmu/core/joiner_general.cpp
  storage/tianmu/core/joiner_mapped.cpp
  storage/tianmu/core/mi_iterator.h
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/core/parameterized_filter.h
  storage/tianmu/core/proxy_hash_joiner.cpp
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/core/task_executor.h
  storage/tianmu/core/tools.h
  storage/tianmu/core/value_matching_table.h
  storage/tianmu/index/rc_table_index.cpp
  storage/tianmu/index/rdb_meta_manager.cpp
  storage/tianmu/mm/tcm/tccommon.cpp
  storage/tianmu/system/cacheable_item.cpp
  storage/tianmu/types/bstring.cpp
  storage/tianmu/types/rc_data_types.h
Labels: PR-feature

#943 fix(tianmu): fix LEFT JOIN query result err with WHERE IS NULL clause (#887)
  mysql-test/suite/tianmu/r/issue887.result
  mysql-test/suite/tianmu/t/issue887.test
  storage/tianmu/core/condition.h
  storage/tianmu/core/cq_term.h
  storage/tianmu/core/descriptor.cpp
  storage/tianmu/core/descriptor.h
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/core/parameterized_filter.h
  storage/tianmu/core/temp_table.cpp
Labels: PR-bug

#936 fix(workflow): rm duplicate libreadline-dev in lib preparation #687
  .github/workflows/integration-compile-mtryml
Labels: PR-bug

#935 fix(workflow): rm duplicate libreadline-dev in lib preparaion #687
  .github/workflows/integration-compile-mtryml
Labels: PR-bug

#940 fix(tianmu):query with UNION ALL return result set error.(#854)
  mysql-test/suite/tianmu/r/union.result
  mysql-test/suite/tianmu/t/union.test
  storage/tianmu/core/engine_execute.cpp
Labels: PR-bug

#946 feat(my.cnf):change my.cnf log、undolog、redolog and socket dir
  scripts/my.cnf.sample
Labels: PR-feature

#910 fix(tianmu): fix query syntax (WHERE NOT IN ) is not supported. (#767)
  mysql-test/suite/tianmu/r/issue767.result
  mysql-test/suite/tianmu/t/issue767.test
  storage/tianmu/core/query.cpp
Labels: PR-bug

#961 fix(tiamu): select...in...An error was reported when the date was included(#829)
  mysql-test/suite/tianmu/r/issue829.result
  mysql-test/suite/tianmu/t/issue829.test
  storage/tianmu/types/rc_datetime.cpp
Labels: PR-bug

#978 fix(CI/CD):change lint runs-on:ubuntu-20.04
  .github/workflows/pull_requests.yml
Labels: PR-bug

#970 fix(tianmu): fix Load DPN when the table is empty (#964)
  mysql-test/suite/tianmu/r/issue964.result
  mysql-test/suite/tianmu/t/issue964.test
  storage/tianmu/core/rc_attr.cpp
Labels: PR-bug

#922 feat(tianmu): Improve the performance of master slave synchronization and the performance of the execution interface for modifying data(#889)
  mysql-test/suite/tianmu/r/delete.result
  mysql-test/suite/tianmu/r/issue819.result
  mysql-test/suite/tianmu/r/issue889.result
  mysql-test/suite/tianmu/t/delete.test
  mysql-test/suite/tianmu/t/issue819.test
  mysql-test/suite/tianmu/t/issue889.test
  sql/CMakeLists.txt
  sql/log_event.cc
  sql/log_event.h
  sql/log_event_push_cond.cc
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/pack.cpp
  storage/tianmu/core/pack.h
  storage/tianmu/core/pack_int.cpp
  storage/tianmu/core/pack_str.cpp
  storage/tianmu/core/pack_str.h
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/core/rc_table.h
  storage/tianmu/handler/tianmu_handler.cpp
  storage/tianmu/handler/tianmu_handler_com.cpp
  storage/tianmu/index/rc_table_index.cpp
  storage/tianmu/system/configuration.cpp
  storage/tianmu/system/configuration.h
  storage/tianmu/util/thread_pool.h
Labels: PR-feature

#991 docs(Limits): update the docs
  Docs/00-about-stonedb/limits.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/limits.md
  website/i18n/zh/docusaurus-plugin-content-pages/index.md
  website/src/pages/index.md
Labels: PR-docs

#993 test(mtr): add some mtr testcases(#497)
  mysql-test/suite/tianmu/r/aggregate.result
  mysql-test/suite/tianmu/r/create_view.result
  mysql-test/suite/tianmu/r/date_formats_func.result
  mysql-test/suite/tianmu/r/in_subquery.result
  mysql-test/suite/tianmu/r/insert_into_select.result
  mysql-test/suite/tianmu/r/various_join.result
  mysql-test/suite/tianmu/t/aggregate.test
  mysql-test/suite/tianmu/t/create_view.test
  mysql-test/suite/tianmu/t/date_formats_func.test
  mysql-test/suite/tianmu/t/in_subquery.test
  mysql-test/suite/tianmu/t/insert_into_select.test
  mysql-test/suite/tianmu/t/various_join.test
Labels: PR-testing

#999 feat(tianmu): revert compress refactor code. (#11)
  storage/tianmu/compress/word_graph.cpp
  storage/tianmu/compress/word_graph.h
Labels: PR-feature

#1004 test(mtr): add mtr testcases(#497)
  mysql-test/suite/tianmu/r/between_and.result
  mysql-test/suite/tianmu/r/coalesce_ascii_func.result
  mysql-test/suite/tianmu/r/convert_conv_func.result
  mysql-test/suite/tianmu/r/different_charsets_a.result
  mysql-test/suite/tianmu/r/div_func.result
  mysql-test/suite/tianmu/r/func_define.result
  mysql-test/suite/tianmu/r/insert_all_data_types.result
  mysql-test/suite/tianmu/r/replace_func.result
  mysql-test/suite/tianmu/t/between_and.test
  mysql-test/suite/tianmu/t/coalesce_ascii_func.test
  mysql-test/suite/tianmu/t/convert_conv_func.test
  mysql-test/suite/tianmu/t/different_charsets_a.test
  mysql-test/suite/tianmu/t/div_func.test
  mysql-test/suite/tianmu/t/func_define.test
  mysql-test/suite/tianmu/t/insert_all_data_types.test
  mysql-test/suite/tianmu/t/replace_func.test
Labels: PR-testing

#986 feat(tianmu): support "alter table t_test comment 'abc'" ddl. (#985)
  mysql-test/suite/tianmu/r/issue985.result
  mysql-test/suite/tianmu/t/issue985.test
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#1023 fix(tianmu): revert suffix_tree.h constructor. (#11)
  storage/tianmu/compress/suffix_tree.h
Labels: PR-bug

#1027 docs(Readme): update the Readme
  Docs/stonedb_wecaht_group.jpg
  Docs/stonedb_wecaht_group.png
  README.md
  README_zh-hans.md
Labels: PR-docs

#1033 fix(CI/CD):change clint os to ubuntu-20.04
  .github/workflows/pull_requests.yml
Labels: PR-bug

#912 fix(tianmu): fix query syntax (WHERE NOT IN ) is not supported. (#767)
  mysql-test/suite/tianmu/r/issue767.result
  mysql-test/suite/tianmu/t/issue767.test
  storage/tianmu/core/compiled_query.cpp
  storage/tianmu/core/joiner.cpp
  storage/tianmu/core/query.cpp
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/core/temp_table.cpp
  storage/tianmu/core/temp_table.h
Labels: PR-bug

#1005 feat(tianmu): To support Binlog in mandatory tianmu engine mode (#956)
  mysql-test/suite/tianmu/r/issue819.result
  mysql-test/suite/tianmu/r/issue956.result
  mysql-test/suite/tianmu/t/issue819.test
  mysql-test/suite/tianmu/t/issue956.test
  sql/sql_class.h
  sql/sql_parse.cc
  sql/sql_table.cc
  sql/sys_vars.cc
Labels: PR-feature

#1035 docs: fix typo in quick deployment doc
  Docs/02-getting-started/quick-deployment/quick-deployment-57.md
Labels: PR-docs

#1039 feat(CI/CD):fix stonedb80 clint error
  .github/workflows/pull_requests.yml
Labels: PR-feature

#1032 fix(tianmu): fix bug: cmake .. -DENABLE_GCOV=1 faild. (#1031)
  storage/tianmu/base/net/posix_stack.cpp
  storage/tianmu/base/net/posix_stack.h
Labels: PR-bug
