Repository stoneatom/stonedb, pull requests merged in 2022-10, with the labels that each got.

#633 feat(tianmu): Delete the added code to find root cause (#541)
  sql/sql_optimizer.cc
  storage/tianmu/core/query_compile.cpp
Labels: PR-feature

#636 feat(Tianmu): set system variable "tianmu_large_prefix" default value from OFF to ON. (#631)
  storage/tianmu/handler/tianmu_handler_com.cpp
Labels: PR-feature

#639 feat(StoneDB 8.0): fix up the compiling 'cast-qual' warnings. (#547)
  storage/tianmu/common/common_definitions.h
  storage/tianmu/compress/dictionary.cpp
  storage/tianmu/compress/num_compressor.h
  storage/tianmu/compress/part_dict.cpp
  storage/tianmu/compress/top_bit_dict.h
  storage/tianmu/core/bin_tools.cpp
  storage/tianmu/core/bin_tools.h
  storage/tianmu/core/condition_encoder.cpp
  storage/tianmu/core/descriptor.cpp
  storage/tianmu/core/dimension_group.cpp
  storage/tianmu/core/dimension_group_virtual.cpp
  storage/tianmu/core/mysql_expression.cpp
  storage/tianmu/core/mysql_expression.h
  storage/tianmu/core/pack_int.cpp
  storage/tianmu/core/rc_mem_table.cpp
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/core/rcattr_exeq_rs.cpp
  storage/tianmu/core/temp_table.cpp
  storage/tianmu/core/value_or_null.h
  storage/tianmu/handler/ha_rcengine.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/index/rdb_meta_manager.cpp
  storage/tianmu/system/file.cpp
  storage/tianmu/system/net_stream.cpp
  storage/tianmu/types/bstring.cpp
  storage/tianmu/types/rc_data_types.h
  storage/tianmu/types/rc_datetime.cpp
  storage/tianmu/types/rc_num.cpp
  storage/tianmu/types/rc_num.h
  storage/tianmu/vc/expr_column.cpp
Labels: PR-feature

#638 feat(StoneDB 8.0): Replace Query_result::prepare2() with Query_result::start_execution. (#539)
  storage/tianmu/core/engine_execute.cpp
Labels: PR-feature, C-stonedb-8.0

#640 feat(StoneDB 8.0): Fix up the compiling warnings(miscellaneous). (#547)
  storage/tianmu/async_tests/main.cc
  storage/tianmu/async_tests/task_executor.h
  storage/tianmu/base/core/iostream_impl.h
  storage/tianmu/base/core/sleep.h
  storage/tianmu/base/net/posix_stack.cpp
  storage/tianmu/common/compile_opts.h
  storage/tianmu/common/exception.h
  storage/tianmu/compress/text_compressor.cpp
  storage/tianmu/core/column.h
  storage/tianmu/core/compiled_query.cpp
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine_results.cpp
  storage/tianmu/core/groupby_wrapper.cpp
  storage/tianmu/core/index_table.cpp
  storage/tianmu/core/item_tianmu_field.h
  storage/tianmu/core/joiner.cpp
  storage/tianmu/core/joiner_hash.cpp
  storage/tianmu/core/joiner_mapped.cpp
  storage/tianmu/core/mi_iterator.h
  storage/tianmu/core/mysql_expression.cpp
  storage/tianmu/core/proxy_hash_joiner.cpp
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/core/rcattr_exqp.cpp
  storage/tianmu/core/sorter3.cpp
  storage/tianmu/core/sorter_wrapper.cpp
  storage/tianmu/core/task_executor.h
  storage/tianmu/core/temp_table.h
  storage/tianmu/core/temp_table_low.cpp
  storage/tianmu/core/tools.h
  storage/tianmu/exporter/export2file.cpp
  storage/tianmu/exporter/export2file.h
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/index/rc_table_index.cpp
  storage/tianmu/mm/tcm/tccommon.cpp
  storage/tianmu/system/rc_system.cpp
  storage/tianmu/system/rc_system.h
  storage/tianmu/types/rc_data_types.h
  storage/tianmu/util/log_ctl.cpp
  storage/tianmu/util/log_ctl.h
  storage/tianmu/vc/subselect_column.cpp
Labels: PR-feature, C-stonedb-8.0

#642 fix(ISSUE_TEMPLATE): Fix formatting errors
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: PR-bug

#644 feat(tianmu): Improve tianmu readability(#11)
  sql/sql_load.cc
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_my_tianmu.h
  storage/tianmu/handler/ha_rcengine.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/handler/ha_tianmu.h
Labels: PR-feature

#653 feat(StoneDB 8.0):add complier image by centos 7(#652)
  .github/workflows/compile-mtr.yml
Labels: PR-feature

#654 feat(tianm): Improve Tianm readability (#11)
  storage/tianmu/core/compilation_tools.cpp
  storage/tianmu/core/compilation_tools.h
  storage/tianmu/core/engine.h
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/query.cpp
  storage/tianmu/core/query.h
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_my_tianmu.h
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#645 feat(StoneDB 8.0): Fix up overloaded-virtual warning in function select_tianmu_export::prepare. (#547)
  storage/tianmu/exporter/export2file.cpp
  storage/tianmu/exporter/export2file.h
Labels: PR-feature, C-stonedb-8.0

#655 feat(StoneDB 8.0): Fix up format-security/class-memaccess warnings. (#547)
  storage/tianmu/compress/part_dict.cpp
  storage/tianmu/core/dpn.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/rcattr_exeq_rs.cpp
Labels: PR-feature, C-stonedb-8.0

#657 fix(StoneDB 8.0): fix ERROR 2013 (HY000): Lost connection to MySQL server during query. (#650)
  storage/tianmu/core/engine.cpp
Labels: PR-bug, C-stonedb-8.0

#600 fix(handler): fix the bug for create table #mysql50#q.q should return…
  mysql-test/suite/tianmu/r/issue487.result
  mysql-test/suite/tianmu/t/issue487.test
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-bug

#668 fix(StoneDB 8.0):clang-format check storage/tianmu(#667)
  .github/workflows/compile-mtr.yml
Labels: PR-bug

#666 feat(tianmu): introduce the JOIN::optimize to tianmu (#545)
  sql/sql_optimizer.cc
  sql/sql_optimizer.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/engine_results.cpp
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
Labels: PR-feature

#690 feat(tianmu): Introudce the JOIN::optimize to Tianmu (#545)
  sql/sql_lex.h
  storage/tianmu/core/compilation_tools.cpp
  storage/tianmu/core/compilation_tools.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/engine.ic
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/query.cpp
  storage/tianmu/core/query.h
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_my_tianmu.h
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/util/timer.cpp
  storage/tianmu/util/timer.h
Labels: PR-feature

#683 feat(StoneDB 8.0): adapt the Tianmu engine query interface to MySQL8.0 (#681)
  mysql-test/suite/tianmu/t/group_concat.testbak
  sql/conn_handler/socket_connection.cc
  sql/sql_cmd_ddl_table.cc
  sql/sql_select.cc
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/query.h
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/types/rc_item_types.cpp
Labels: PR-feature, C-stonedb-8.0

#693 fix(tianmu): add file extension of tianmu into hton to fix drop database error #662
  mysql-test/suite/tianmu/t/dropdb.test
  sql/handler.cc
  sql/mysqld.cc
  sql/mysqld.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/handler/ha_rcengine.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/handler/ha_tianmu.h
Labels: PR-bug

#679 ci/cd(website): Restore CI/CD for website(#672)
  .github/workflows/website-deploy.yml
Labels: PR-improvement

#709 feature(tianmu): check whether there is least one tianmu table in Query_expression (#708)
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/util/timer.cpp
  storage/tianmu/util/timer.h
Labels: C-stonedb-8.0

#712 feature(tianmu): sql command "show status" support "tianmu status variables". (#711)
  mysql-test/suite/tianmu/r/issue703.result
  mysql-test/suite/tianmu/t/issue703.test
  storage/tianmu/handler/tianmu_handler_com.cpp
Labels: PR-feature

#713 doc(tianmu): Delete invalid docs
  Docs/04-developer-guide/01-connect-to-stonedb/navicat-step1.png
  Docs/04-developer-guide/01-connect-to-stonedb/navicat-step2.png
  Docs/04-developer-guide/01-connect-to-stonedb/navicat-step3.png
  Docs/04-developer-guide/01-connect-to-stonedb/use-navicat.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/01-connect-to-stonedb/Navicat_step1.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/01-connect-to-stonedb/Navicat_step2.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/01-connect-to-stonedb/Navicat_success.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/01-connect-to-stonedb/use-navicat.md
Labels: A-documentation, PR-docs

#714 feat(tianmu): To support ARM arch (#696).
  storage/tianmu/base/core/cacheline.h
  storage/tianmu/base/core/reactor.cpp
  storage/tianmu/base/core/thread.cpp
  storage/tianmu/base/util/spinlock.h
  storage/tianmu/core/bin_tools.h
  storage/tianmu/core/tools.h
Labels: PR-feature

#704 feat(StoneDB 8.0): sql command "show status" support "tianmu status variables". (#703)
  mysql-test/suite/tianmu/r/issue703.result
  mysql-test/suite/tianmu/t/issue703.test
  storage/tianmu/handler/ha_rcengine.cpp
Labels: PR-feature, C-stonedb-8.0

#677 fix(StoneDB 8.0):rename pull_requests.yml and change make -j`nproc`
  .github/workflows/pull_requests.yml
Labels: PR-bug

#647 fix(stonedb): fix problem caused by concatenated calls of multiple triggers.(#580)
  mysql-test/suite/tianmu/r/trigger.result
  mysql-test/suite/tianmu/t/trigger.test
  sql/handler.cc
  sql/sql_delete.cc
  storage/tianmu/core/rc_table.cpp
Labels: PR-bug

#716 feat(tianmu):fix code to repair `order by` command (#715)
  sql/sql_cmd_ddl_table.cc
  sql/sql_select.cc
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.ic
Labels: PR-feature, C-stonedb-8.0

#721 feat(tianmu): to adapt `group by` command to MySQL8.0.(#718)
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.ic
  storage/tianmu/core/query_compile.cpp
Labels: PR-feature, C-stonedb-8.0

#725 fix(mtr):rename *.testbak to *.test and repair some test case
  mysql-test/suite/tianmu/r/issue228.result
  mysql-test/suite/tianmu/r/issue502.result
  mysql-test/suite/tianmu/r/issues_tx417.result
  mysql-test/suite/tianmu/r/lz4.result
  mysql-test/suite/tianmu/r/orquery.result
  mysql-test/suite/tianmu/r/orquery1.result
  mysql-test/suite/tianmu/t/issue228.test
  mysql-test/suite/tianmu/t/issue228.testbak
  mysql-test/suite/tianmu/t/issue417.test
  mysql-test/suite/tianmu/t/issue429.test
  mysql-test/suite/tianmu/t/issue431.test
  mysql-test/suite/tianmu/t/issue467.test
  mysql-test/suite/tianmu/t/issue468.test
  mysql-test/suite/tianmu/t/issue469.test
  mysql-test/suite/tianmu/t/issue475.test
  mysql-test/suite/tianmu/t/issue496.test
  mysql-test/suite/tianmu/t/issue502.test
  mysql-test/suite/tianmu/t/issues_tx417.test
  mysql-test/suite/tianmu/t/lz4.test
  mysql-test/suite/tianmu/t/orquery.test
  mysql-test/suite/tianmu/t/orquery1.test
Labels: PR-bug

#720 feat(handler): improve code readability #719
  storage/tianmu/handler/ha_rcengine.cpp
Labels: PR-feature

#724 feat(StoneDB 8.0): add some mtr test case. (#723)
  mysql-test/suite/tianmu/r/alter_table_v1.result
  mysql-test/suite/tianmu/t/alter_table_v1.test
Labels: PR-feature

#728 feat(tianmu): Introudce the JOIN::optimize to Tianmu(#545)
  sql/sql_optimizer.cc
  storage/tianmu/core/engine.ic
  storage/tianmu/core/query_compile.cpp
Labels: PR-feature

#730 feature(tianmu): to support explain the table of Tianmu engine (#726)
  sql/sql_cmd_ddl_table.cc
  sql/sql_select.cc
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.ic
  storage/tianmu/core/query.h
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_my_tianmu.h
Labels: C-stonedb-8.0

#739 style(clangformat): change the parameter of clangformat AllowShortIfS…
  storage/tianmu/.clang-format
Labels: PR-style

#729 feat(StoneDB 8.0): tianmu_insert_delayed decides the binary log file events. (#723)
  mysql-test/suite/tianmu/r/issue723-1.result
  mysql-test/suite/tianmu/r/issue723-2.result
  mysql-test/suite/tianmu/t/alter_table_v1-master.opt
  mysql-test/suite/tianmu/t/issue723-1-master.opt
  mysql-test/suite/tianmu/t/issue723-1.test
  mysql-test/suite/tianmu/t/issue723-2-master.opt
  mysql-test/suite/tianmu/t/issue723-2.test
  sql/sql_insert.cc
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_my_tianmu.h
Labels: PR-feature

#740 fix(tianmu): Solve the problem of query failure when a=a occurs in the predicate or. (#301, #733)
  mysql-test/suite/tianmu/r/issue301.result
  mysql-test/suite/tianmu/r/issue431.result
  mysql-test/suite/tianmu/r/issue468.result
  mysql-test/suite/tianmu/t/issue301.test
  sql/sql_optimizer.cc
Labels: PR-bug

#750 feat(cmake): update tianmu cmake file(#749)
  storage/tianmu/CMakeLists.txt
Labels: PR-feature

#742 feat(StoneDB 8.0): adapt mtr 'issue364.test'. (#723)
  mysql-test/suite/tianmu/r/issue364.result
  mysql-test/suite/tianmu/t/issue364.test
Labels: PR-feature

#753 feat(StoneDB 8.0): support view query,adapt mtr "issue342" testcase. (#743)
  mysql-test/suite/tianmu/r/issue342.result
  mysql-test/suite/tianmu/t/issue342.test
  sql/sql_optimizer.cc
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_my_tianmu.h
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#764 feat(workflow):add nightly CI/CD workflows
  .github/workflows/nightly.yml
Labels: PR-feature

#762 fix(tianmu): the instance crashed while use derived table(#761)
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-bug

#766 test(mtr):[modified]tianmu/t/issue415.test
  mysql-test/suite/tianmu/r/issue415.result
  mysql-test/suite/tianmu/t/issue415.test
Labels: PR-testing

#756 fix(core): fix the bug of incorrect result set of count function (#736)
  mysql-test/suite/tianmu/r/issue736.result
  mysql-test/suite/tianmu/t/issue736.test
  storage/tianmu/core/group_distinct_table.cpp
Labels: PR-bug

#765 fix(tianmu): fix bug:'on duplicate key update' scenario, incorrect result occurs. (#502)
  mysql-test/suite/tianmu/r/issue502-2.result
  mysql-test/suite/tianmu/t/issue502-2.test
  sql/protocol_classic.cc
Labels: PR-bug

#775 fix(tianmu): Fixed tianmu syntax compatibility issue when continuous equivalent predicates are eliminated (#733)
  mysql-test/suite/tianmu/r/issue301.result
  mysql-test/suite/tianmu/t/issue301.test
  sql/sql_optimizer.cc
Labels: A-bug, PR-bug

#776 fix(tianmu): feature: The error display is too general, and the cause of the error cannot be clearly located #706
  storage/tianmu/common/exception.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/engine_results.cpp
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/handler/ha_rcengine.cpp
  storage/tianmu/system/file.cpp
  storage/tianmu/types/rc_datetime.cpp
Labels: PR-bug

#772 feat(StoneDB 8.0): adapt mtr test cases:issue502-2/issues_tx417/issue496/issue745. (#770)
  mysql-test/suite/tianmu/r/issue475.result
  mysql-test/suite/tianmu/r/issue502-2.result
  mysql-test/suite/tianmu/t/issue502-2.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine_results.cpp
  storage/tianmu/core/query_compile.cpp
Labels: PR-feature

#778 fix(workflow):fix warning and add mtr test
  .github/workflows/nightly.yml
Labels: PR-bug

#780 feat(tianmu): adapt update mtr testcase for MySQL 8.0 (#779)
  storage/tianmu/handler/ha_tianmu.h
Labels: PR-feature, C-stonedb-8.0

#789 fix(website): Delete the old configuration(#785)
  website/package-lock.json
  website/src/components/icon/index.tsx
  website/src/components/icon/styles.ts
  website/src/pages/index.tsx
  website/src/pages/styles/panel.ts
  website/src/theme/BlogLayout/index.tsx
  website/src/theme/BlogLayout/styles.ts
  website/src/theme/BlogPostItem/styles.module.css
  website/src/theme/Navbar/MobileSidebar/Header/index.tsx
  website/src/theme/Navbar/MobileSidebar/PrimaryMenu/index.tsx
  website/src/theme/Navbar/MobileSidebar/SecondaryMenu/index.tsx
  website/src/theme/Navbar/MobileSidebar/Toggle/index.tsx
  website/src/theme/TOCItems/Tree.tsx
  website/src/theme/TOCItems/index.tsx
Labels: PR-feature, PR-bug

#787 fix(tianmu): feature: The error display is too general, and the cause of the error cannot be clearly located #706
  storage/tianmu/.clang-format
  storage/tianmu/common/exception.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/engine_results.cpp
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/system/file.cpp
  storage/tianmu/types/rc_datetime.cpp
Labels: PR-bug

#802 fix(website): Deleting an Incorrect Configuration(#801)
  website/docusaurus.config.js
  website/i18n/zh/docusaurus-theme-classic/navbar.json
Labels: PR-bug, PR-docs

#798 test(mtr): Add update_signed.test and delete_signed.test(#497)
  mysql-test/suite/tianmu/r/delete_signed.result
  mysql-test/suite/tianmu/r/update_signed.result
  mysql-test/suite/tianmu/t/delete_signed.test
  mysql-test/suite/tianmu/t/update_signed.test
Labels: PR-testing

#806 test(mtr):add delete_join.test and modified issue515.test(#497)
  mysql-test/suite/tianmu/r/delete_join.result
  mysql-test/suite/tianmu/t/delete_join.test
  mysql-test/suite/tianmu/t/issue515.test
Labels: PR-testing

#810 test(mtr): Add select_precision.test and select_distinct.test(#497)
  mysql-test/suite/tianmu/r/select_distinct.result
  mysql-test/suite/tianmu/r/select_precision.result
  mysql-test/suite/tianmu/t/select_distinct.test
  mysql-test/suite/tianmu/t/select_precision.test
Labels: PR-testing

#812 fix(tianmu):EXPLAIN query Q4, MySQL server has gone away (#727)
  storage/tianmu/core/query_compile.cpp
Labels: PR-bug

#815 test(mtr):add select_joins.test(#497)
  mysql-test/suite/tianmu/r/if_function.result
  mysql-test/suite/tianmu/r/select_expressions.result
  mysql-test/suite/tianmu/r/select_function_calls.result
  mysql-test/suite/tianmu/r/select_joins.result
  mysql-test/suite/tianmu/r/select_order_by_group_by.result
  mysql-test/suite/tianmu/r/truncate_table.result
  mysql-test/suite/tianmu/t/if_function.test
  mysql-test/suite/tianmu/t/select_expressions.test
  mysql-test/suite/tianmu/t/select_function_calls.test
  mysql-test/suite/tianmu/t/select_joins.test
  mysql-test/suite/tianmu/t/select_order_by_group_by.test
  mysql-test/suite/tianmu/t/truncate_table.test
Labels: PR-testing

#805 fix(tianmu): bug for truncate table failed #759
  mysql-test/suite/tianmu/r/truncate.result
  mysql-test/suite/tianmu/t/truncate.test
  sql/sql_truncate.cc
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/transaction.cpp
Labels: PR-bug

#816 feat(StoneDB 8.0): adapt "mysqld --version" feature. (#813)
  CMakeLists.txt
  sql/build_info.h.ini
  sql/mysqld.cc
Labels: PR-feature

#824 test(mtr):add cast_data_types.result and time_function.test(#497)
  mysql-test/suite/tianmu/r/cast_data_types.result
  mysql-test/suite/tianmu/r/time_function.result
  mysql-test/suite/tianmu/t/cast_data_types.test
  mysql-test/suite/tianmu/t/time_function.test
Labels: PR-testing

#799 feat(StoneDB 8.0): adapt testcase insert_select.test/flow_control_function.test. (#777)
  mysql-test/suite/tianmu/r/flow_control_function.result
  mysql-test/suite/tianmu/r/insert_select.result
  mysql-test/suite/tianmu/t/flow_control_function.test
  mysql-test/suite/tianmu/t/insert_select.test
  sql/sql_insert.cc
Labels: PR-feature

#828 test(mtr):add function testcase(#497)
  mysql-test/suite/tianmu/r/hour_function.result
  mysql-test/suite/tianmu/r/insert_on_duplicate_update.result
  mysql-test/suite/tianmu/r/last_day_function.result
  mysql-test/suite/tianmu/r/left_function.result
  mysql-test/suite/tianmu/r/mid_function.result
  mysql-test/suite/tianmu/r/right_function.result
  mysql-test/suite/tianmu/r/substr_function.result
  mysql-test/suite/tianmu/r/substring_function.result
  mysql-test/suite/tianmu/r/timediff_function.result
  mysql-test/suite/tianmu/r/timestampadd_function.result
  mysql-test/suite/tianmu/r/timestampdiff_function.result
  mysql-test/suite/tianmu/r/week_function.result
  mysql-test/suite/tianmu/r/weekday_function.result
  mysql-test/suite/tianmu/r/weekofyear_function.result
  mysql-test/suite/tianmu/r/year_function.result
  mysql-test/suite/tianmu/r/yearweek_function.result
  mysql-test/suite/tianmu/t/hour_function.test
  mysql-test/suite/tianmu/t/insert_on_duplicate_update.test
  mysql-test/suite/tianmu/t/last_day_function.test
  mysql-test/suite/tianmu/t/left_function.test
  mysql-test/suite/tianmu/t/mid_function.test
  mysql-test/suite/tianmu/t/right_function.test
  mysql-test/suite/tianmu/t/substr_function.test
  mysql-test/suite/tianmu/t/substring_function.test
  mysql-test/suite/tianmu/t/timediff_function.test
  mysql-test/suite/tianmu/t/timestampadd_function.test
  mysql-test/suite/tianmu/t/timestampdiff_function.test
  mysql-test/suite/tianmu/t/week_function.test
  mysql-test/suite/tianmu/t/weekday_function.test
  mysql-test/suite/tianmu/t/weekofyear_function.test
  mysql-test/suite/tianmu/t/year_function.test
  mysql-test/suite/tianmu/t/yearweek_function.test
Labels: PR-testing

#825 feat(mtr): add create table test in mtr #695
  mysql-test/suite/tianmu/r/create_table.result
  mysql-test/suite/tianmu/t/create_table.test
Labels: PR-feature

#833 feat(StoneDB 8.0): fix memory leak using valgrind(definitely lost memory). (#817)
  mysql-test/suite/tianmu/t/issue723-2.test
  storage/tianmu/core/engine.ic
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature, C-stonedb-8.0

#831 feat(tianmu): Improve the readbility of stonedb. (#11)
  storage/tianmu/compress/arith_coder.cpp
  storage/tianmu/compress/arith_coder.h
  storage/tianmu/compress/basic_data_filt.cpp
  storage/tianmu/compress/basic_data_filt.h
  storage/tianmu/compress/bit_stream_compressor.cpp
  storage/tianmu/compress/code_stream.h
  storage/tianmu/compress/data_filt.h
  storage/tianmu/compress/data_stream.cpp
  storage/tianmu/compress/data_stream.h
  storage/tianmu/compress/defs.h
  storage/tianmu/compress/dictionary.cpp
  storage/tianmu/compress/dictionary.h
  storage/tianmu/compress/inc_alloc.cpp
  storage/tianmu/compress/inc_alloc.h
  storage/tianmu/compress/inc_wgraph.cpp
  storage/tianmu/compress/inc_wgraph.h
  storage/tianmu/compress/num_compressor.h
  storage/tianmu/compress/part_dict.h
  storage/tianmu/compress/ppm.cpp
  storage/tianmu/compress/ppm.h
  storage/tianmu/compress/ppm_defs.h
  storage/tianmu/compress/range_code.h
  storage/tianmu/compress/suffix_tree.cpp
  storage/tianmu/compress/suffix_tree.h
  storage/tianmu/compress/text_compressor.cpp
  storage/tianmu/compress/text_compressor.h
  storage/tianmu/compress/top_bit_dict.cpp
  storage/tianmu/compress/top_bit_dict.h
  storage/tianmu/compress/word_graph.cpp
  storage/tianmu/compress/word_graph.h
  storage/tianmu/core/aggregator_advanced.cpp
  storage/tianmu/core/aggregator_basic.cpp
  storage/tianmu/core/cached_buffer.cpp
  storage/tianmu/core/column_bin_encoder.cpp
  storage/tianmu/core/condition_encoder.cpp
  storage/tianmu/core/descriptor.cpp
  storage/tianmu/core/engine_convert.cpp
  storage/tianmu/core/just_a_table.cpp
  storage/tianmu/core/rc_attr.cpp
  storage/tianmu/core/rcattr_exeq_rs.cpp
  storage/tianmu/core/rcattr_exqp.cpp
  storage/tianmu/core/rsi_bloom.cpp
  storage/tianmu/core/rsi_cmap.cpp
  storage/tianmu/core/value_or_null.cpp
  storage/tianmu/exporter/data_exporter_txt.cpp
  storage/tianmu/loader/load_parser.cpp
  storage/tianmu/loader/value_cache.cpp
  storage/tianmu/system/channel_out.h
  storage/tianmu/types/bstring.cpp
  storage/tianmu/types/rc_data_types.h
  storage/tianmu/types/rc_datetime.cpp
  storage/tianmu/types/rc_num.cpp
  storage/tianmu/types/rc_num.h
  storage/tianmu/types/rc_value_object.cpp
  storage/tianmu/types/value_parser4txt.cpp
  storage/tianmu/vc/const_column.cpp
  storage/tianmu/vc/single_column.cpp
Labels: PR-feature

#838 test(mtr): add aliases.test type_timestamp.test modified issue415.tes…
  mysql-test/suite/tianmu/r/aliases.result
  mysql-test/suite/tianmu/r/issue415.result
  mysql-test/suite/tianmu/r/type_timestamp.result
  mysql-test/suite/tianmu/t/aliases.test
  mysql-test/suite/tianmu/t/issue415.test
  mysql-test/suite/tianmu/t/type_timestamp.test
Labels: PR-testing

#832 feat(StoneDB 8.0): Improve the readbility of stonedb. (#11)
  storage/tianmu/compress/arith_coder.cpp
  storage/tianmu/compress/arith_coder.h
  storage/tianmu/compress/basic_data_filt.cpp
  storage/tianmu/compress/basic_data_filt.h
  storage/tianmu/compress/bit_stream_compressor.cpp
  storage/tianmu/compress/code_stream.h
  storage/tianmu/compress/data_filt.h
  storage/tianmu/compress/data_stream.cpp
  storage/tianmu/compress/data_stream.h
  storage/tianmu/compress/defs.h
  storage/tianmu/compress/dictionary.cpp
  storage/tianmu/compress/dictionary.h
  storage/tianmu/compress/inc_alloc.cpp
  storage/tianmu/compress/inc_alloc.h
  storage/tianmu/compress/inc_wgraph.cpp
  storage/tianmu/compress/inc_wgraph.h
  storage/tianmu/compress/num_compressor.h
  storage/tianmu/compress/part_dict.h
  storage/tianmu/compress/ppm.cpp
  storage/tianmu/compress/ppm.h
  storage/tianmu/compress/ppm_defs.h
  storage/tianmu/compress/range_code.h
  storage/tianmu/compress/suffix_tree.cpp
  storage/tianmu/compress/suffix_tree.h
  storage/tianmu/compress/text_compressor.cpp
  storage/tianmu/compress/text_compressor.h
  storage/tianmu/compress/top_bit_dict.cpp
  storage/tianmu/compress/top_bit_dict.h
  storage/tianmu/compress/word_graph.cpp
  storage/tianmu/compress/word_graph.h
  storage/tianmu/core/aggregator_advanced.cpp
  storage/tianmu/core/aggregator_basic.cpp
  storage/tianmu/core/cached_buffer.cpp
  storage/tianmu/core/column_bin_encoder.cpp
  storage/tianmu/core/condition_encoder.cpp
  storage/tianmu/core/descriptor.cpp
  storage/tianmu/core/engine_convert.cpp
  storage/tianmu/core/just_a_table.cpp
  storage/tianmu/core/rc_attr.cpp
  storage/tianmu/core/rcattr_exeq_rs.cpp
  storage/tianmu/core/rcattr_exqp.cpp
  storage/tianmu/core/rsi_bloom.cpp
  storage/tianmu/core/rsi_cmap.cpp
  storage/tianmu/core/value_or_null.cpp
  storage/tianmu/exporter/data_exporter_txt.cpp
  storage/tianmu/loader/load_parser.cpp
  storage/tianmu/loader/value_cache.cpp
  storage/tianmu/system/channel_out.h
  storage/tianmu/types/bstring.cpp
  storage/tianmu/types/rc_data_types.h
  storage/tianmu/types/rc_datetime.cpp
  storage/tianmu/types/rc_num.cpp
  storage/tianmu/types/rc_num.h
  storage/tianmu/types/rc_value_object.cpp
  storage/tianmu/types/value_parser4txt.cpp
  storage/tianmu/vc/const_column.cpp
  storage/tianmu/vc/single_column.cpp
Labels: PR-feature

#841 feat(tianmu):Improve the readbility of stonedb.(#11)
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/handler/ha_tianmu.h
Labels: PR-feature, C-stonedb-8.0

#843 fix(tianmu): group_concat.test has in-consistent behavior in CICD and prompt mode (#834)
  mysql-test/suite/tianmu/r/group_concat.result
  mysql-test/suite/tianmu/r/group_concat2.result
  mysql-test/suite/tianmu/t/group_concat.test
  mysql-test/suite/tianmu/t/group_concat2.test
  storage/tianmu/core/aggregation_algorithm.cpp
  storage/tianmu/core/aggregation_algorithm.h
  storage/tianmu/core/engine_convert.cpp
  storage/tianmu/core/group_table.cpp
  storage/tianmu/core/group_table.h
Labels: PR-bug

#839 feat(tianmu):Improve the readbility of stonedb.(#11)
  storage/tianmu/handler/ha_rcengine.cpp
  storage/tianmu/handler/tianmu_handler.cpp
  storage/tianmu/handler/tianmu_handler.h
  storage/tianmu/handler/tianmu_handler_com.cpp
Labels: PR-feature, C-stonedb-5.7

#842 feat(tianmu): Improve the readbility of stonedb. (#11)
  storage/tianmu/common/common_definitions.h
  storage/tianmu/common/data_format.cpp
  storage/tianmu/common/data_format.h
  storage/tianmu/common/exception.h
  storage/tianmu/common/sequence_generator.h
Labels: PR-feature

#856 test(mtr): Add alter_table_negative.test and union.test(#497)
  mysql-test/suite/tianmu/r/alter_table_negative.result
  mysql-test/suite/tianmu/r/union.result
  mysql-test/suite/tianmu/t/alter_table_negative.test
  mysql-test/suite/tianmu/t/union.test
Labels: PR-testing
