Repository stoneatom/stonedb, pull requests merged in 2022-07, with the labels that each got.

#139 fix(github): ci/cd not can't trigger normally (#138)
  .github/workflows/integration-compile-mtr.yml
  CMakeLists.txt
Labels: PR-bug

#140 fix(stonedb) Valgrind problems(#142)
  storage/perfschema/pfs_server.cc
  storage/stonedb/core/engine.cpp
  storage/stonedb/index/kv_store.cpp
  storage/stonedb/system/cacheable_item.cpp
Labels: PR-bug

#184 feat(stonedb):change default config file stonedb.cnf->my.cnf
  include/mysql_version.h.in
Labels: PR-feature, PR-bug, PR-docs, PR-testing, PR-performance, PR-improvement

#185 fix(docs): dependencies cause deploy problem
  website/yarn.lock
Labels: PR-feature, PR-bug, PR-docs, PR-testing, PR-performance, PR-improvement

#192 fix(mtr):fix innodb-wl5980-linux result
  mysql-test/suite/innodb/r/innodb-wl5980-linux.result
Labels: PR-bug

#201 fix(CI/CD): fix the CI/CD configuration of the document and update introduction(#200)
  .github/workflows/website-deploy.yml
  Docs/00-about-stonedb/intro.md
Labels: PR-bug, PR-docs

#210 feat(workflow): add pr title check in mergify (#207)
  .mergify.yml
Labels: PR-feature

#196 feat(mtr): fix the wrong result of the test case in the mysql-test/r. (#191)
  mysql-test/r/1st.result
  mysql-test/r/ctype_gb18030_encoding_cn.result
  mysql-test/r/ctype_gb18030_encoding_utf8.result
  mysql-test/r/drop.result
  mysql-test/r/events_grant.result
  mysql-test/r/events_scheduling.result
  mysql-test/r/gis-debug.result
  mysql-test/r/grant_debug.result
  mysql-test/r/join_outer.result
  mysql-test/r/log_tables_upgrade.result
  mysql-test/r/mysql_config_editor.result
  mysql-test/r/mysql_plugin.result
  mysql-test/r/mysql_upgrade.result
  mysql-test/r/mysql_upgrade_ssl.result
  mysql-test/r/mysql_upgrade_with_session_user.result
  mysql-test/r/mysqlcheck.result
  mysql-test/r/mysqld--help-notwin.result
  mysql-test/r/mysqldump_bugs.result
  mysql-test/r/mysqlslap.result
  mysql-test/r/no_binlog_gtid_empty_transaction.result
  mysql-test/r/no_binlog_gtid_mode_on.result
  mysql-test/r/no_binlog_gtid_mode_on_explicit_prepared_stmts.result
  mysql-test/r/opt_costmodel_downgrade.result
  mysql-test/r/opt_costmodel_flush.result
  mysql-test/r/opt_hints_pfs.result
  mysql-test/r/signal.result
Labels: PR-feature

#225 Fix(docs): fix compile-using-ubuntu2004.md (#224)
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004.md
Labels: A-documentation

#230 fix(mtr): fix failed charset related test cases (#227)
  mysql-test/character_set/ctype_latin1.test
  mysql-test/character_set/ctype_recoding.test
  mysql-test/character_set/ddl_i18n_koi8r.test
  mysql-test/character_set/ddl_i18n_utf8.test
  mysql-test/character_set/events_2.test
  mysql-test/character_set/events_bugs.test
  mysql-test/character_set/explain.test
  mysql-test/character_set/grant.test
  mysql-test/character_set/lowercase_table.test
  mysql-test/character_set/mysqlpump_charset.test
  mysql-test/character_set/opt_hints.test
  mysql-test/character_set/partition_charset.test
  mysql-test/character_set/plugin_auth.test
  mysql-test/character_set/show_check.test
  mysql-test/character_set/sp.test
Labels: PR-bug

#240 docs(StoneDB): update Chinese docs(#239)
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/architecture.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/intro.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/limits.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/terms.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/download.md
Labels: PR-docs

#241 fix(stonedb): fix up error: NoAttrs was not declared in this scope(#146)
  storage/stonedb/core/aggregation_algorithm.cpp
  storage/stonedb/core/aggregator_advanced.cpp
  storage/stonedb/core/aggregator_advanced.h
  storage/stonedb/core/compiled_query.h
  storage/stonedb/core/condition_encoder.cpp
  storage/stonedb/core/engine.cpp
  storage/stonedb/core/filter.cpp
  storage/stonedb/core/filter.h
  storage/stonedb/core/filter_block.cpp
  storage/stonedb/core/group_distinct_table.cpp
  storage/stonedb/core/just_a_table.h
  storage/stonedb/core/mi_new_contents.cpp
  storage/stonedb/core/mi_updating_iterator.cpp
  storage/stonedb/core/rc_attr.cpp
  storage/stonedb/core/rc_attr.h
  storage/stonedb/core/rc_table.cpp
  storage/stonedb/core/rc_table.h
  storage/stonedb/core/rcattr_exeq_rs.cpp
  storage/stonedb/core/rcattr_exqp.cpp
  storage/stonedb/core/temp_table.cpp
  storage/stonedb/core/temp_table.h
  storage/stonedb/core/temp_table_com.cpp
  storage/stonedb/core/temp_table_low.cpp
  storage/stonedb/core/temp_table_roughquery.cpp
  storage/stonedb/handler/stonedb_handler.cpp
  storage/stonedb/loader/load_parser.cpp
  storage/stonedb/vc/subselect_column.cpp
Labels: PR-bug

#255 feat(stonedb): set the default engine to stonedb (#253)
  install_scripts/my.cnf
Labels: PR-feature

#238 feat(stonedb): add docs issue templates(#235)
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: PR-feature

#262 docs(stonedb): update the doc of compile-using-docker（#261）
  Docs/04-developer-guide/00-compiling-methods/compile-using-docker.md
Labels: PR-docs

#258 docs(Functions): Update documentation for supported functions（#257）
  Docs/05-SQL-reference/04-functions/advanced-functions.md
  Docs/05-SQL-reference/04-functions/aggregate-functions.md
  Docs/05-SQL-reference/04-functions/date-and-time-functions.md
  Docs/05-SQL-reference/04-functions/mathematical-functions.md
  Docs/05-SQL-reference/04-functions/string-functions.md
Labels: PR-docs

#254 docs(stonedb ): update some docs（#252）
  Docs/00-about-stonedb/architecture.md
  Docs/00-about-stonedb/limits.md
  Docs/00-about-stonedb/stonedb-V1.png
  Docs/00-about-stonedb/stonedb-architecture-V1.png
  Docs/04-developer-guide/statements-for-queries.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/architecture.md
Labels: PR-docs

#260 feat(stonedb): Improve the readability of stonedb(#259)
  storage/stonedb/core/condition_encoder.cpp
  storage/stonedb/core/descriptor.cpp
  storage/stonedb/core/dimension_group_virtual.cpp
  storage/stonedb/core/filter.cpp
  storage/stonedb/core/filter.h
  storage/stonedb/core/multi_index.cpp
  storage/stonedb/core/parallel_hash_join.cpp
  storage/stonedb/core/parameterized_filter.cpp
  storage/stonedb/core/rc_attr.cpp
  storage/stonedb/core/rc_attr.h
  storage/stonedb/core/rc_table.h
  storage/stonedb/core/rcattr_exeq_rs.cpp
  storage/stonedb/core/rcattr_exqp.cpp
  storage/stonedb/handler/stonedb_handler.cpp
  storage/stonedb/vc/in_set_column.cpp
  storage/stonedb/vc/in_set_column.h
  storage/stonedb/vc/multi_value_column.h
  storage/stonedb/vc/subselect_column.cpp
  storage/stonedb/vc/subselect_column.h
Labels: PR-feature

#288 docs(Stonedb): fix docs deploy problem.(#287)
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/stonedb-V1-zhCN.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/05-SQL-reference/04-functions/advanced-functions.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/05-SQL-reference/04-functions/date-and-time-functions.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/05-SQL-reference/04-functions/mathematical-functions.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/05-SQL-reference/04-functions/string-functions.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/04-database-tuning/sql-best-practices.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/01-OLTP/oltp-performance-test-method.md
  website/yarn.lock
Labels: PR-bug, PR-docs

#267 fix(sql): fix crash when executing sql statement (#212)
  sql/sql_show.cc
Labels: PR-bug

#295 docs(stonedb): fix issue (#291) and (#293), update a document
  Docs/03-O&M-Guide/00-monitoring-and-alerting/prometheus+grafana-monitor.md
  website/i18n/zh/docusaurus-plugin-content-docs/current.json
  website/i18n/zh/docusaurus-plugin-content-docs/current/01-environment-requirements/supported-servers-and-oss.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/03-O&M-Guide/00-monitoring-and-alerting/prometheus+grafana-monitor.md
Labels: PR-docs

#303 docs: fix(#287) deployment errors caused by some symbols
  Docs/03-O&M-Guide/00-monitoring-and-alerting/prometheus+grafana-monitor.md
  Docs/06-performance-tuning/04-database-tuning/sql-best-practices.md
  Docs/06-performance-tuning/04-database-tuning/sql-tuning.md
  Docs/08-troubleshooting/slow-query.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/04-database-tuning/sql-tuning.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/08-troubleshooting/slow-query.md
Labels: PR-docs

#316 docs: rich doc to fix env dependence "not found"(#304)
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment.md
Labels: PR-docs

#317 fix(mtr): make the mtr passed (#315)
  .github/workflows/integration-compile-mtr.yml
  mysql-test/include/default_mysqld.cnf
  mysql-test/suite/stonedb/t/issue410.testbak
  mysql-test/suite/stonedb/t/issue415.testbak
  mysql-test/suite/stonedb/t/issue433.testbak
  mysql-test/suite/stonedb/t/issue446.testbak
  mysql-test/suite/stonedb/t/issue515.testbak
  mysql-test/suite/stonedb/t/load.testbak
Labels: PR-bug

#324 feat(stonedb): update the copyright date time (#321)
  client/base/help_options.cc
  client/check/mysqlcheck.cc
  client/mysql.cc
  client/mysql_config_editor.cc
  client/mysql_install_db.cc
  client/mysql_secure_installation.cc
  client/mysql_ssl_rsa_setup.cc
  client/mysqladmin.cc
  client/mysqlbinlog.cc
  client/mysqldump.c
  client/mysqlimport.c
  client/mysqlshow.c
  client/mysqlslap.cc
  client/mysqltest.cc
  extra/innochecksum.cc
  extra/lz4_decompress.cc
  extra/my_print_defaults.c
  extra/perror.c
  extra/resolve_stack_dump.cc
  include/welcome_copyright_notice.h
  sql/gen_lex_hash.cc
  sql/gen_lex_token.cc
  sql/mysqld.cc
  storage/archive/archive_reader.c
  storage/myisam/myisampack.c
Labels: PR-feature

#328 fix(core): fix crash when executing sql. (#327)
  .gitignore
  storage/stonedb/core/query.cpp
Labels: PR-bug

#312 feat(index): Unified class member variable name with google style (#311)
  storage/stonedb/core/engine.cpp
  storage/stonedb/core/engine.h
  storage/stonedb/core/rc_attr.cpp
  storage/stonedb/core/rc_attr.h
  storage/stonedb/core/rc_table.cpp
  storage/stonedb/index/kv_store.cpp
  storage/stonedb/index/kv_store.h
  storage/stonedb/index/kv_transaction.cpp
  storage/stonedb/index/kv_transaction.h
  storage/stonedb/index/rc_table_index.cpp
  storage/stonedb/index/rc_table_index.h
  storage/stonedb/index/rdb_meta_manager.cpp
  storage/stonedb/index/rdb_meta_manager.h
Labels: PR-feature
