Repository stoneatom/stonedb, pull requests merged in 2022-09, with the labels that each got.

#464 docs(ci/cd&content): Update the CI/CD of the document website and download link (#463)
  .github/workflows/website-deploy.yml
  Docs/download.md
  website/docusaurus.config.js
  website/i18n/zh/docusaurus-plugin-content-docs/current/download.md
Labels: PR-docs

#468 docs: in english version document some place describe stonedb as row-based #467
  Docs/00-about-stonedb/architecture.md
  Docs/02-getting-started/basic-operations.md
  Docs/02-getting-started/quick-start.md
  Docs/03-O&M-Guide/01-backup-and-recovery/use-mydumper-full-backup.md
  Docs/03-O&M-Guide/regular-change-operations.md
  Docs/04-developer-guide/01-connect-to-stonedb/use-mysql-client.md
  Docs/04-developer-guide/04-create-and-manage-database-objects/create-and-manage-stored-procedure.md
  Docs/04-developer-guide/04-create-and-manage-database-objects/create-and-manage-table.md
  Docs/04-developer-guide/DML-starements.md
Labels: PR-docs

#473 fix(tianmu): fix stonedb has two LZ4 versions (#471)
  cmake/lz4.cmake
  extra/lz4/lz4-1.9.4/LICENSE
  extra/lz4/lz4-1.9.4/lz4.c
  extra/lz4/lz4-1.9.4/lz4.h
  extra/lz4/lz4-1.9.4/lz4file.c
  extra/lz4/lz4-1.9.4/lz4file.h
  extra/lz4/lz4-1.9.4/lz4frame.c
  extra/lz4/lz4-1.9.4/lz4frame.h
  extra/lz4/lz4-1.9.4/lz4frame_static.h
  extra/lz4/lz4-1.9.4/lz4hc.c
  extra/lz4/lz4-1.9.4/lz4hc.h
  extra/lz4/lz4-1.9.4/xxhash.c
  extra/lz4/lz4-1.9.4/xxhash.h
  storage/tianmu/compress/lz4.cpp
  storage/tianmu/compress/lz4.h
  storage/tianmu/compress/text_compressor.cpp
  storage/tianmu/core/pack_str.cpp
Labels: PR-bug

#457 feat(tianmu): Support (Single-Table Syntax) DELETE FROM tb_name
  mysql-test/include/have_tianmu.inc
  mysql-test/suite/tianmu/r/delete_all_rows.result
  mysql-test/suite/tianmu/t/delete_all_rows.test
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-feature

#480 docs(Compiling Methods): update the latest docs(#476)
  Docs/04-developer-guide/00-compiling-methods/5.6-boost.png
  Docs/04-developer-guide/00-compiling-methods/5.6-marisa.png
  Docs/04-developer-guide/00-compiling-methods/5.6-rocksdb.png
  Docs/04-developer-guide/00-compiling-methods/5.7-boost.png
  Docs/04-developer-guide/00-compiling-methods/5.7-marisa.png
  Docs/04-developer-guide/00-compiling-methods/5.7-rocksdb.png
  Docs/04-developer-guide/00-compiling-methods/compile-using-centos7-for-56.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-centos7-for-57.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-redhat7-for-56.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-redhat7-for-57.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004-for-56.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004-for-57.md
  Docs/release-notes.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/5.6-boost.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/5.6-marisa.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/5.6-rocksdb.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/5.7-boost.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/5.7-marisa.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/5.7-rocksdb.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-centos7-for-56.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-centos7-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-redhat7-for-56.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-redhat7-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004-for-56.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/release-notes.md
Labels: PR-docs

#485 docs(tianmu): update the latest docs (#484)
  Docs/04-developer-guide/00-compiling-methods/compile-using-centos7-for-56.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-centos7-for-57.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-redhat7-for-56.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-redhat7-for-57.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004-for-56.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004-for-57.md
  README_zh-hans.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/architecture.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/intro.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/stonedb-V1-zhCN.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/basic-operations.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/03-O&M-Guide/01-backup-and-recovery/use-mydumper-full-backup.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/03-O&M-Guide/01-backup-and-recovery/use-mysqldump-backup-and-restore.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-centos7-for-56.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-centos7-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-redhat7-for-56.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-redhat7-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004-for-56.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/05-SQL-reference/04-functions/advanced-functions.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/05-SQL-reference/04-functions/date-and-time-functions.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/05-SQL-reference/04-functions/mathematical-functions.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/05-SQL-reference/04-functions/string-functions.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/04-database-tuning/sql-best-practices.md
Labels: PR-docs

#475 fix(tianmu): fix specified key was too long; max key length is 255 bytes(#228)
  mysql-test/suite/tianmu/r/issue228.result
  mysql-test/suite/tianmu/t/issue228.test
  storage/tianmu/common/common_definitions.h
  storage/tianmu/handler/tianmu_handler.cpp
  storage/tianmu/handler/tianmu_handler.h
  storage/tianmu/handler/tianmu_handler_com.cpp
  storage/tianmu/system/configuration.cpp
  storage/tianmu/system/configuration.h
Labels: PR-bug

#482 feat(tianmu): support alter column length and column type (#411)
  mysql-test/suite/tianmu/r/alter_table.result
  mysql-test/suite/tianmu/t/alter_table.test
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-feature

#494 feat(cicd):add doc pr not use cicd and move .mergify.yml to .github(#486)
  .github/mergify.yml
  .github/workflows/integration-compile-mtr.yml
Labels: PR-feature

#516 docs(tianmu): Correct some command and style errors(#515)
  Docs/02-getting-started/quick-deployment/quick-deployment-57.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-centos7/compile-using-centos7-for-56.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-centos7/compile-using-centos7-for-57.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-redhat7/compile-using-redhat7-for-56.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-redhat7/compile-using-redhat7-for-57.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004/compile-using-ubuntu2004-for-57.md
  Docs/06-performance-tuning/06-performance-tests/00-OLAP/click-memory.png
  Docs/06-performance-tuning/06-performance-tests/00-OLAP/clickhouse-cpu.png
  Docs/06-performance-tuning/06-performance-tests/00-OLAP/clickhouse-disk-iops.png
  Docs/06-performance-tuning/06-performance-tests/00-OLAP/clickhouse-system-load.png
  Docs/06-performance-tuning/06-performance-tests/00-OLAP/stonedb-cpu.png
  Docs/06-performance-tuning/06-performance-tests/00-OLAP/stonedb-disk-iops.png
  Docs/06-performance-tuning/06-performance-tests/00-OLAP/stonedb-memory.png
  Docs/06-performance-tuning/06-performance-tests/00-OLAP/stonedb-system-load.png
  Docs/06-performance-tuning/06-performance-tests/00-OLAP/tcph-test-report.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/quick-deployment-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-centos7/compile-using-centos7-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-redhat7/compile-using-redhat7-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004/compile-using-ubuntu2004-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/click-memory.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/clickhouse-cpu.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/clickhouse-disk-iops.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/clickhouse-system-load.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/stonedb-cpu.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/stonedb-disk-iops.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/stonedb-memory.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/stonedb-system-load.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/stonedb-vs-clickhouse.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/06-performance-tuning/06-performance-tests/00-OLAP/tcph-test-report.md
Labels: PR-docs

#503 test(mtr):add insert,create....The test script(#497)
  mysql-test/include/default_mysqld.cnf
  mysql-test/suite/tianmu/r/create_db.result
  mysql-test/suite/tianmu/r/create_index.result
  mysql-test/suite/tianmu/r/create_table.result
  mysql-test/suite/tianmu/r/dropdb.result
  mysql-test/suite/tianmu/r/insert.result
  mysql-test/suite/tianmu/r/select.result
  mysql-test/suite/tianmu/t/create_db.test
  mysql-test/suite/tianmu/t/create_index.test
  mysql-test/suite/tianmu/t/create_table.test
  mysql-test/suite/tianmu/t/dropdb.test
  mysql-test/suite/tianmu/t/insert.test
  mysql-test/suite/tianmu/t/select.test
  mysql-test/suite/tianmu/t/select_tpch-master.opt
Labels: PR-testing

#523 docs(README): fix urls of README(#522)
  README.md
  README_zh-hans.md
Labels: PR-docs

#519 fix(mergify):fix docs pr cant automerge and pr title check error (#518)
  .github/mergify.yml
Labels: PR-bug

#496 fix(tianmu): fix the instance crashed while loading data (#462)
  storage/tianmu/common/common_definitions.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/rc_attr.cpp
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/core/transaction.h
Labels: PR-bug

#533 fix(stonedb): add missing files provoke by .gitignore #532
  .gitignore
  components/test/keyring_encryption_test/CMakeLists.txt
  components/test/keyring_encryption_test/components.cc
  components/test/keyring_encryption_test/components.h
  components/test/keyring_encryption_test/keyring_encryption.cc
  components/test/keyring_encryption_test/options.cc
  components/test/keyring_encryption_test/options.h
  extra/curl/curl-7.83.1/COPYING
  extra/icu/icu-release-69-1/source/common/common.vcxproj
  extra/icu/icu-release-69-1/source/common/common.vcxproj.filters
  extra/icu/icu-release-69-1/source/common/common_uwp.vcxproj
  extra/icu/icu-release-69-1/source/i18n/i18n.vcxproj
  extra/icu/icu-release-69-1/source/i18n/i18n.vcxproj.filters
  extra/icu/icu-release-69-1/source/i18n/i18n_uwp.vcxproj
  extra/icu/icu-release-69-1/source/stubdata/stubdata.vcxproj
  extra/icu/icu-release-69-1/source/stubdata/stubdata.vcxproj.filters
  extra/icu/icudt69b/brkitr/de.res
  extra/icu/icudt69b/brkitr/el.res
  extra/icu/icudt69b/brkitr/en.res
  extra/icu/icudt69b/brkitr/en_US.res
  extra/icu/icudt69b/brkitr/en_US_POSIX.res
  extra/icu/icudt69b/brkitr/es.res
  extra/icu/icudt69b/brkitr/fr.res
  extra/icu/icudt69b/brkitr/it.res
  extra/icu/icudt69b/brkitr/ja.res
  extra/icu/icudt69b/brkitr/pt.res
  extra/icu/icudt69b/brkitr/res_index.res
  extra/icu/icudt69b/brkitr/root.res
  extra/icu/icudt69b/brkitr/ru.res
  extra/icu/icudt69b/brkitr/zh.res
  extra/icu/icudt69b/brkitr/zh_Hant.res
  extra/icu/icudt69l/brkitr/de.res
  extra/icu/icudt69l/brkitr/el.res
  extra/icu/icudt69l/brkitr/en.res
  extra/icu/icudt69l/brkitr/en_US.res
  extra/icu/icudt69l/brkitr/en_US_POSIX.res
  extra/icu/icudt69l/brkitr/es.res
  extra/icu/icudt69l/brkitr/fr.res
  extra/icu/icudt69l/brkitr/it.res
  extra/icu/icudt69l/brkitr/ja.res
  extra/icu/icudt69l/brkitr/pt.res
  extra/icu/icudt69l/brkitr/res_index.res
  extra/icu/icudt69l/brkitr/root.res
  extra/icu/icudt69l/brkitr/ru.res
  extra/icu/icudt69l/brkitr/zh.res
  extra/icu/icudt69l/brkitr/zh_Hant.res
  extra/libedit/libedit-20210910-3.1/COPYING
  extra/protobuf/protobuf-3.19.4/src/libprotobuf-lite.map
  extra/protobuf/protobuf-3.19.4/src/libprotobuf.map
  extra/protobuf/protobuf-3.19.4/src/libprotoc.map
  extra/protobuf/protobuf-3.19.4/src/solaris/libstdc++.la
  extra/zlib/zlib-1.2.12/zlib.map
  extra/zstd/zstd-1.5.0/COPYING
  packaging/deb-in/extra/conf.d/mysql.cnf
  router/src/harness/src/logging/eventlog_rc/MSG00001.bin
  router/src/harness/tests/data/logger.d/default.cfg
  router/src/harness/tests/data/logger.d/magic.cfg
  router/src/harness/tests/data/logger.d/one.cfg
  storage/ndb/src/common/logger/MSG00001.bin
Labels: PR-bug

#531 feat(stonedb8.0:load binlog): support mysql load binlog. (#530)
  sql/sql_load.h
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/handler/ha_rcengine.cpp
Labels: PR-feature

#556 fix(stonedb8.0): fix Tianmu engine for union primary key crash (#534)
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-bug

#563 docs(tianmu): Update docs and contributors (#561)
  Docs/00-about-stonedb/architecture.md
  Docs/00-about-stonedb/intro.md
  Docs/02-getting-started/quick-start.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-docker.md
  website/i18n/zh/docusaurus-plugin-content-blog-community/main.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/architecture.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/intro.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/08-troubleshooting/resource-bottleneck.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/09-FAQ/troubleshoot-faq.md
Labels: PR-docs

#565 fix(mergify): fix incorrect lable name PR-Docs to PR-docs #564
  .github/mergify.yml
Labels: PR-bug

#552 feat(stonedb8.0): mysql load sql with set clause should report warning. (#551)
  storage/tianmu/core/engine.cpp
Labels: PR-feature

#572 feat(StoneDB 8.0): parent_lex->result is nullptr in "select ... from" clause without "into outfile/dumpfile". (#557)
  storage/tianmu/core/engine.cpp
Labels: PR-feature

#575 feat(StoneDB 8.0): thd->no_errors no_errors is deleted. (#574)
  storage/tianmu/handler/tianmu_handler_com.cpp
Labels: PR-feature

#573 fix(tianmu): The current version does not enable multithreaded aggregation optimization (#567)
  storage/tianmu/core/aggregation_algorithm.cpp
Labels: A-improvement

#585 feat(StoneDB 8.0): refactor ConditionNumberFromMultipleEquality function. (#583)
  storage/tianmu/core/query.cpp
Labels: PR-feature

#588 feat(StoneDB 8.0): change mysql8.0 boost directory & add cmake of marisa and rocksdb
  CMakeLists.txt
  cmake/boost.cmake
  cmake/marisa.cmake
  cmake/rocksdb.cmake
Labels: PR-feature

#592 feat(StoneDB 8.0): Fix up the compiling extra-semi warnings. (#547)
  storage/tianmu/base/core/execution_stage.h
  storage/tianmu/base/core/expiring_fifo.h
  storage/tianmu/base/core/future.h
  storage/tianmu/base/core/reactor.h
  storage/tianmu/base/net/api.h
  storage/tianmu/base/net/posix_stack.cpp
  storage/tianmu/base/net/posix_stack.h
  storage/tianmu/base/net/stack.h
  storage/tianmu/core/bloom_block.h
  storage/tianmu/core/column_type.h
  storage/tianmu/core/compiled_query.h
  storage/tianmu/core/descriptor.h
  storage/tianmu/core/dimension_group.h
  storage/tianmu/core/dimension_vector.h
  storage/tianmu/core/filter.h
  storage/tianmu/core/joiner_mapped.h
  storage/tianmu/core/just_a_table.h
  storage/tianmu/core/pack_orderer.h
  storage/tianmu/core/query.h
  storage/tianmu/core/rc_attr.h
  storage/tianmu/core/rough_multi_index.h
  storage/tianmu/core/rsi_histogram.h
  storage/tianmu/core/sorter3.h
  storage/tianmu/core/temp_table.h
  storage/tianmu/core/transaction.h
  storage/tianmu/exporter/export2file.h
  storage/tianmu/index/kv_store.h
  storage/tianmu/index/rc_table_index.h
  storage/tianmu/index/rdb_meta_manager.h
  storage/tianmu/system/channel.h
  storage/tianmu/system/channel_out.h
  storage/tianmu/system/file_out.h
  storage/tianmu/types/rc_data_types.h
  storage/tianmu/types/rc_item_types.h
  storage/tianmu/types/value_parser4txt.h
  storage/tianmu/vc/virtual_column_base.h
Labels: PR-feature

#594 feat(StoneDB 8.0): Query_block->braces is deleted by MySQL 8.0 (#593)
  storage/tianmu/core/engine_execute.cpp
Labels: PR-feature

#591 fix(tianmu): Switches are added to support controlling whether multithreading is used to nested loops (#578)
  storage/tianmu/core/joiner.h
  storage/tianmu/core/joiner_general.cpp
Labels: PR-bug

#562 feat(StoneDB 8.0): Fix codes aboout JoinType. (#543)
  storage/tianmu/core/compiled_query.cpp
  storage/tianmu/core/descriptor.h
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/query.cpp
  storage/tianmu/core/query.h
  storage/tianmu/core/query_compile.cpp
Labels: PR-feature

#604 feat(StoneDB 8.0): Field::ptr is a protected member. (#603)
  sql/field.h
  storage/tianmu/core/engine_convert.cpp
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-feature

#602 feat(StoneDB 8.0): st_select_lex::set_join is deleted in mysql8.0. (#598)
  sql/sql_lex.cc
  sql/sql_lex.h
  storage/tianmu/core/engine_execute.cpp
Labels: PR-feature, C-stonedb-8.0

#607 feat(StoneDB 8.0): fix stonedb 8.0 compile failed (#606)
  CMakeLists.txt
  client/dump/CMakeLists.txt
  cmake/boost.cmake
  cmake/fastcov.cmake
  plugin/keyring_udf/CMakeLists.txt
  sql/CMakeLists.txt
  unittest/gunit/CMakeLists.txt
Labels: A-feature, PR-feature

#611 feat(CI/CD):chenge CI/CD use compile-mtr.yml(#610)
  .github/workflows/compile-mtr.yml
  .github/workflows/integration-compile-mtryml
  .github/workflows/website-deployyml
Labels: PR-feature

#616 fix(StoneDB 8.0):change mergify configure check-success(#612)
  .github/mergify.yml
Labels: PR-bug

#622 fix(mergify):change mergify configure check-success(#621)
  .github/mergify.yml
Labels: PR-bug

#617 feat(StoneDB 8.0): lex->derived_tables & thd->fill_derived_tables() is deleted in MySQL8.0. (#548)
  storage/tianmu/core/engine_execute.cpp
Labels: PR-feature

#615 feat(StoneDB 8.0): 'bool partitioned' parameter is added by MySQL 8.0 in handlerton->create function. (#596)
  storage/tianmu/handler/tianmu_handler.cpp
  storage/tianmu/handler/tianmu_handler.h
  storage/tianmu/handler/tianmu_handler_com.cpp
Labels: PR-feature

#623 feat(StoneDB 8.0): dd::Table * parameter is added by MySQL 8.0 in handle api. (#595)
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-feature

#628 feat(tianmu): Changes the names of file to follow the convention(#576)
  sql/sql_load.cc
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_my_tianmu.h
  storage/tianmu/handler/ha_rcengine.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/handler/ha_tianmu.h
  storage/tianmu/handler/tianmu_handler_com.cpp
  storage/tianmu/index/rc_table_index.cpp
Labels: PR-feature

#630 feat(StoneDB 8.0): remove 'build' from .gitignore file. (#629)
  .gitignore
Labels: PR-feature, C-stonedb-8.0
