Repository stoneatom/stonedb, pull requests merged in 2022-08, with the labels that each got.

#313 docs: fix bugs of #309 and #310
  website/docusaurus.config.js
  website/src/theme/MDXComponents/Image.tsx
Labels: PR-docs

#325 feat(stonedb): To support gcc 7.5 or higher and fix up error(#11)(#12)
  .github/workflows/integration-compile-mtr.yml
  CMakeLists.txt
  cmake/boost.cmake
  cmake/marisa.cmake
  cmake/rocksdb.cmake
  storage/stonedb/CMakeLists.txt
  storage/stonedb/async_tests/CMakeLists.txt
  storage/stonedb/base/core/app_template.h
  storage/stonedb/base/core/reactor.h
  storage/stonedb/base/core/scollectd_impl.h
  storage/stonedb/core/rc_mem_table.cpp
  storage/stonedb/core/rc_mem_table.h
  storage/stonedb/core/task_executor.cpp
  storage/stonedb/core/temp_table.h
  storage/stonedb/core/temp_table_roughquery.cpp
  storage/stonedb/index/kv_store.cpp
  storage/stonedb/index/kv_store.h
  storage/stonedb/index/rdb_utils.h
  storage/stonedb/vc/const_expr_column.h
  storage/stonedb/vc/subselect_column.cpp
Labels: PR-feature

#365 fix(core): Double prepare on lex unit for ctas with union(#226)
  mysql-test/suite/tianmu/r/issue226.result
  mysql-test/suite/tianmu/t/issue226.test
  storage/tianmu/core/engine_execute.cpp
Labels: PR-bug

#363 fix(tianmu): fix group_concat_max_len warning (#338)
  sql/sys_vars.cc
Labels: PR-bug

#373 docs(stonedb): update docs and fix bugs
  Docs/02-getting-started/quick-deployment.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-centos7.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-redhat7.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004.md
  Docs/images/compile-stonedb-on-ubuntu2004/boost_dir.png
  Docs/images/compile-stonedb-on-ubuntu2004/marisa_dir.png
  Docs/images/compile-stonedb-on-ubuntu2004/rocks_dir.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-centos7.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-redhat7.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/libboost.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/libmarisa.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/librocksdb.png
  website/src/theme/MDXComponents/Image.tsx
Labels: PR-docs

#355 feat(doc):doc add innodb backup to stonedb demonstrate（#353）
  website/i18n/zh/docusaurus-plugin-content-docs/current/03-O&M-Guide/01-backup-and-recovery/use-mydumper-full-backup.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/03-O&M-Guide/01-backup-and-recovery/use-mysqldump-backup-and-restore.md
Labels: PR-feature

#376 feat(innodb): To support compiling innodb as C++ 17(#374)
  storage/innobase/include/univ.i
  storage/innobase/include/ut0new.h
Labels: PR-feature

#382 feat(stonedb): To support unspecify the location of 3rd libs(#12).
  CMakeLists.txt
Labels: PR-feature

#377 feat(stonedb):To support gcc 9 and `WITH_ROCKSDB` and `WITH_MARISA` (#12)
  .github/workflows/integration-compile-mtr.yml
  CMakeLists.txt
  cmake/boost.cmake
  cmake/marisa.cmake
  cmake/rocksdb.cmake
  storage/tianmu/CMakeLists.txt
  storage/tianmu/async_tests/CMakeLists.txt
Labels: PR-feature

#379 fix(mtr): Add test cases for NULL value select on UNIQUE constraint(#281)
  mysql-test/suite/tianmu/r/issue281.result
  mysql-test/suite/tianmu/t/issue281.test
Labels: PR-bug

#346 fix(core): Added handling of CACHE_ITEM type in MysqlExpression(#342)
  storage/tianmu/core/mysql_expression.cpp
Labels: PR-bug

#392 docs(stonedb): update the latest docs(#391)
  Docs/00-about-stonedb/KnowledgeGrid-1.png
  Docs/00-about-stonedb/KnowledgeGrid-2.png
  Docs/00-about-stonedb/KnowledgeGrid-3.png
  Docs/00-about-stonedb/architecture.md
  Docs/00-about-stonedb/intro.md
  Docs/00-about-stonedb/limits.md
  Docs/00-about-stonedb/stonedb-architecture-V1.png
  Docs/00-about-stonedb/terms.md
  Docs/01-environment-requirements/server-configuration-requirements.md
  Docs/01-environment-requirements/supported-servers-and-OSs.md
  Docs/02-getting-started/basic-operations.md
  Docs/02-getting-started/quick-deploy-in-docker.md
  Docs/02-getting-started/quick-deployment.md
  Docs/02-getting-started/quick-start.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/KnowledgeGrid-1.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/KnowledgeGrid-2.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/KnowledgeGrid-3.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/architecture.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/intro.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/limits.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/stonedb-V1-zhCN.png
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/terms.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/01-environment-requirements/server-configuration-requirements.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/01-environment-requirements/supported-servers-and-oss.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/basic-operations.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deploy-in-docker.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-start.md
Labels: PR-docs

#400 fix(tianmu): Fix crashes caused by transaction errors when autocommit=1(#364)
  mysql-test/suite/tianmu/r/issue364.result
  mysql-test/suite/tianmu/t/issue364.test
  storage/tianmu/handler/tianmu_handler.cpp
Labels: PR-bug

#399 docs(stonedb): fix the errors on a batch of documents (#398)
  .github/ISSUE_TEMPLATE/documentation.yml
  Docs/00-about-stonedb/stonedb-architecture-V1.png
  Docs/01-environment-requirements/supported-servers-and-OSs.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/limits.md
Labels: PR-docs

#390 fix(doc):rm docker build and optimization steps(#389)
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-docker.md
Labels: PR-bug

#407 react(tianmu): refactor some code about tianmu engine(#11)
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/handler/tianmu_handler_com.cpp
  storage/tianmu/index/kv_store.cpp
  storage/tianmu/index/kv_store.h
  storage/tianmu/index/kv_transaction.cpp
  storage/tianmu/index/rc_table_index.cpp
  storage/tianmu/index/rc_table_index.h
  storage/tianmu/index/rdb_meta_manager.cpp
  storage/tianmu/index/rdb_meta_manager.h
Labels: C-stonedb-5.7, PR-improvement

#406 fix(handler):Fix Tianmu engine to support master-slave replication of binlog in ro…
  storage/tianmu/handler/tianmu_handler.h
Labels: PR-bug

#418 fix(core): fixed crash caused by using transaction statements(#417)
  mysql-test/suite/tianmu/r/issues_tx417.result
  mysql-test/suite/tianmu/t/issues_tx417-master.opt
  mysql-test/suite/tianmu/t/issues_tx417.test
  storage/tianmu/core/engine.cpp
Labels: PR-bug

#445 docs(README): add Chinese version (#443)
  Docs/01-environment-requirements/supported-servers-and-OperatingSystems.md
  Docs/stonedb_architecture.png
  Docs/stonedb_overview.png
  Docs/stonedb_wecaht_group.jpg
  README.md
  README_zh-hans.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/03-O&M-Guide/regular-change-operations.md
Labels: A-documentation, PR-docs

#444 fix(tianmu): fix temporary tables are not available (#441)
  mysql-test/suite/tianmu/r/issue441.result
  mysql-test/suite/tianmu/t/issue441.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/handler/tianmu_handler.cpp
  storage/tianmu/index/rdb_utils.h
Labels: PR-bug

#446 fix(LICENSE):fix LICENSE(#438)
  LICENSE
Labels: PR-bug

#437 feat(tianmu): add unittest module, impl gtestmock #430
  .github/workflows/integration-compile-mtr.yml
  Docs/04-developer-guide/00-compiling-methods/compile-using-centos7.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-redhat7.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004.md
  storage/tianmu/CMakeLists.txt
  storage/tianmu/unittest/CMakeLists.txt
  storage/tianmu/unittest/testgmock.cpp
Labels: PR-feature
