Repository stoneatom/stonedb, pull requests merged in 2022-12, with the labels that each got.

#1048 fix(mtr): mtr suite=tianmu delete timeout after 900 seconds (#1047)
  mysql-test/suite/tianmu/r/delete.result
  mysql-test/suite/tianmu/t/delete.test
Labels: PR-bug

#1053 fix(tianmu): fix query exists with primary key (#971 #944)
  mysql-test/suite/tianmu/r/issue971.result
  mysql-test/suite/tianmu/r/trigger.result
  mysql-test/suite/tianmu/t/issue971.test
  mysql-test/suite/tianmu/t/trigger.test
  storage/tianmu/core/descriptor.cpp
  storage/tianmu/core/descriptor.h
Labels: PR-bug

#1055 fix(tianmu): fix ALTER table DROP primary key is forbidden (#1034)
  mysql-test/suite/tianmu/r/issue1034.result
  mysql-test/suite/tianmu/t/issue1034.test
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1036 fix(tianmu): fix tianmu_num constructor issue. (#11)
  storage/tianmu/types/tianmu_num.cpp
Labels: PR-bug

#1037 fix(tianmu): revert some compress code issue. (#11)
  storage/tianmu/compress/suffix_tree.h
  storage/tianmu/compress/word_graph.h
  storage/tianmu/types/rc_num.cpp
Labels: PR-bug

#1060 feat(tianmu): support unsigned/zerofill #1013
  mysql-test/suite/tianmu/r/func_math.result
  mysql-test/suite/tianmu/t/func_math.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/mysql_expression.cpp
Labels: PR-feature

#972 feat(core): support select ... where like null #669
  mysql-test/suite/tianmu/r/issue410.result
  mysql-test/suite/tianmu/r/issue763.result
  mysql-test/suite/tianmu/t/issue410.test
  mysql-test/suite/tianmu/t/issue763.test
  storage/tianmu/core/query.cpp
Labels: PR-feature

#1067 feat(core): change default log level from INFO to DEBUG in commit phase #1066
  storage/tianmu/core/transaction.cpp
Labels: PR-feature

#1083 docs(optimization): Developer Guide Document Optimization (#1077)
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-centos7/compile-using-centos7-for-57.md
Labels: PR-docs

#1084 fix(tianmu): The predicade pushdown failed lead to the table full scan (#1054)
  mysql-test/suite/tianmu/r/issue1054.result
  mysql-test/suite/tianmu/r/issue1065.result
  mysql-test/suite/tianmu/r/issue228.result
  mysql-test/suite/tianmu/r/issue301.result
  mysql-test/suite/tianmu/t/issue1054.test
  mysql-test/suite/tianmu/t/issue1065.test
  mysql-test/suite/tianmu/t/issue228.test
  mysql-test/suite/tianmu/t/issue301.test
  sql/log_event.cc
  sql/log_event.h
  sql/log_event_push_cond.cc
Labels: PR-bug

#1087 fix(scripts): The compilation script lacks the path parameters of marisa and rocksdb (#1085)
  scripts/stonedb_build.sh
Labels: PR-bug

#1097 fix(tianmu): fix bug: Garbled code occurs after the character set is converted. (#1070)
  mysql-test/suite/tianmu/r/issue1070.result
  mysql-test/suite/tianmu/t/issue1070.test
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1105 feat(tianmu): fix bug: The data type was not determined during load data. (#852)
  mysql-test/suite/tianmu/r/issue1000.result
  mysql-test/suite/tianmu/r/issue852.result
  mysql-test/suite/tianmu/std_data/issue852.txt
  mysql-test/suite/tianmu/t/issue852.test
  storage/tianmu/loader/parsing_strategy.cpp
Labels: PR-feature

#1120 fix(tianmu): Fix the dimension index is -1 leads server to crash(#962)
  mysql-test/suite/tianmu/r/issue962.result
  mysql-test/suite/tianmu/t/issue962.test
  storage/tianmu/core/dimension_vector.h
Labels: PR-bug

#1124 feat(tianmu): Changes the RS to RoughSet makes it meaningful(#11)
  storage/tianmu/common/common_definitions.h
  storage/tianmu/core/bin_tools.cpp
  storage/tianmu/core/bin_tools.h
  storage/tianmu/core/compiled_query.h
  storage/tianmu/core/descriptor.cpp
  storage/tianmu/core/descriptor.h
  storage/tianmu/core/joiner_general.cpp
  storage/tianmu/core/pack_orderer.cpp
  storage/tianmu/core/pack_orderer.h
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/core/parameterized_filter.h
  storage/tianmu/core/physical_column.h
  storage/tianmu/core/query.cpp.bak
  storage/tianmu/core/rough_multi_index.cpp
  storage/tianmu/core/rough_multi_index.h
  storage/tianmu/core/rsi_bloom.cpp
  storage/tianmu/core/rsi_bloom.h
  storage/tianmu/core/rsi_cmap.cpp
  storage/tianmu/core/rsi_cmap.h
  storage/tianmu/core/rsi_histogram.cpp
  storage/tianmu/core/rsi_histogram.h
  storage/tianmu/core/temp_table.cpp
  storage/tianmu/core/temp_table.h
  storage/tianmu/core/temp_table_roughquery.cpp
  storage/tianmu/core/tianmu_attr.h
  storage/tianmu/core/tianmu_attr_exeq_rs.cpp
  storage/tianmu/core/tianmu_attr_exqp.cpp
  storage/tianmu/core/tianmu_table.cpp
  storage/tianmu/vc/const_expr_column.cpp
  storage/tianmu/vc/const_expr_column.h
  storage/tianmu/vc/single_column.cpp
  storage/tianmu/vc/single_column.h
  storage/tianmu/vc/type_cast_column.h
  storage/tianmu/vc/virtual_column_base.cpp
  storage/tianmu/vc/virtual_column_base.h
Labels: PR-feature

#1119 fix(tianmu): fix group by lead to wrong result (#1107)
  mysql-test/suite/tianmu/r/issue1107.result
  mysql-test/suite/tianmu/t/issue1107.test
  storage/tianmu/core/aggregator.h
  storage/tianmu/core/aggregator_basic.cpp
  storage/tianmu/core/group_table.cpp
Labels: PR-bug

#1112 feat(tianmu): support select into outfile with enclosed char. (#850,#1006)
  mysql-test/suite/tianmu/r/issue1006.result
  mysql-test/suite/tianmu/r/issue850.result
  mysql-test/suite/tianmu/std_data/issue1006.txt
  mysql-test/suite/tianmu/std_data/issue850_customer.txt
  mysql-test/suite/tianmu/std_data/issue850_lineorder.txt
  mysql-test/suite/tianmu/std_data/issue850_out.txt
  mysql-test/suite/tianmu/std_data/issue850_part.txt
  mysql-test/suite/tianmu/std_data/issue850_supplier.txt
  mysql-test/suite/tianmu/t/issue1006.test
  mysql-test/suite/tianmu/t/issue850.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/exporter/data_exporter_txt.cpp
  storage/tianmu/exporter/data_exporter_txt.h
  storage/tianmu/loader/parsing_strategy.cpp
  storage/tianmu/system/io_parameters.h
Labels: PR-feature

#1133 test(mtr): add and update some testcases(#497)
  mysql-test/suite/tianmu/r/ctas1.result
  mysql-test/suite/tianmu/r/different_charsets_b.result
  mysql-test/suite/tianmu/r/insert_select.result
  mysql-test/suite/tianmu/r/left_join.result
  mysql-test/suite/tianmu/t/ctas1.test
  mysql-test/suite/tianmu/t/different_charsets_b.test
  mysql-test/suite/tianmu/t/insert_select.test
  mysql-test/suite/tianmu/t/left_join.test
Labels: PR-testing

#1141 docs(readme): fix the link of build(#1139)
  README.md
  README_zh-hans.md
Labels: PR-docs

#1122 feat(tianmu): improve SQL load performance after SQL load feature enhancement. (#1113)
  storage/tianmu/loader/parsing_strategy.cpp
  storage/tianmu/loader/parsing_strategy.h
Labels: PR-feature

#1143 fix(tianmu): mysqld server crash when large amount hash join (#1110)
  storage/tianmu/core/index_table.cpp
  storage/tianmu/core/index_table.h
  storage/tianmu/core/multi_index_builder.h
  storage/tianmu/system/cacheable_item.h
Labels: PR-bug

#1135 test(mtr):add double_float and func_sec_to_time(#497)
  mysql-test/suite/tianmu/r/double_float.result
  mysql-test/suite/tianmu/r/func_sec_to_time.result
  mysql-test/suite/tianmu/t/double_float.test
  mysql-test/suite/tianmu/t/func_sec_to_time.test
Labels: PR-testing

#1081 fix(tianmu): fix alter table add/drop primary key.(#1071)
  mysql-test/suite/tianmu/r/alter_table.result
  mysql-test/suite/tianmu/r/alter_table_primarykey.result
  mysql-test/suite/tianmu/t/alter_table.test
  mysql-test/suite/tianmu/t/alter_table_primarykey-master.opt
  mysql-test/suite/tianmu/t/alter_table_primarykey.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1149 test(mtr): add some test cases(#497)
  mysql-test/include/tianmu_utf8.inc
  mysql-test/suite/tianmu/r/alter_table1.result
  mysql-test/suite/tianmu/r/procedure.result
  mysql-test/suite/tianmu/r/unsigned_least.result
  mysql-test/suite/tianmu/r/user_function.result
  mysql-test/suite/tianmu/t/alter_table1.test
  mysql-test/suite/tianmu/t/procedure.test
  mysql-test/suite/tianmu/t/unsigned_least.test
  mysql-test/suite/tianmu/t/user_function.test
Labels: PR-testing

#1148 feat(tianmu): Refactor the for-loop statement in param filter(#11)
  mysql-test/suite/tianmu/r/issue282.result
  mysql-test/suite/tianmu/t/issue282.test
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/core/parameterized_filter.h
  storage/tianmu/core/query.cpp
  storage/tianmu/core/rough_multi_index.h
  storage/tianmu/core/temp_table.cpp
  storage/tianmu/core/temp_table.h
  storage/tianmu/core/temp_table_com.cpp
  storage/tianmu/core/temp_table_low.cpp
  storage/tianmu/core/temp_table_roughquery.cpp
Labels: PR-feature

#1156 feat(tianmu): SQL load support NULL value. (#1153)
  mysql-test/suite/tianmu/r/issue1153.result
  mysql-test/suite/tianmu/r/issue656.result
  mysql-test/suite/tianmu/r/trigger.result
  mysql-test/suite/tianmu/std_data/issue1153-1.txt
  mysql-test/suite/tianmu/std_data/issue1153-2.txt
  mysql-test/suite/tianmu/t/issue1153.test
  mysql-test/suite/tianmu/t/trigger.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/loader/parsing_strategy.cpp
  storage/tianmu/loader/parsing_strategy.h
Labels: PR-feature

#1150 feat(tianmu):sql_mode set MANDATORY_TIANMU do not work (#1131)
  mysql-test/suite/tianmu/r/issue1131.result
  mysql-test/suite/tianmu/r/issue956.result
  mysql-test/suite/tianmu/t/issue1131.test
  sql/sql_parse.cc
Labels: A-feature, PR-feature

#1126 feat(tianmu):Master slave synchronization - Row format supports primary key scanning(#1111)
  mysql-test/suite/tianmu/r/issue1111.result
  mysql-test/suite/tianmu/t/issue1111.test
  sql/log_event.cc
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature
