Repository stoneatom/stonedb, pull requests merged in 2023-06, with the labels that each got.

#1850 fix(tianmu): revert PR #1841.
  storage/tianmu/vc/tianmu_attr.cpp
Labels: PR-bug

#1852 fix(tianmu): fix up the `group_concat` function in tianmu
  mysql-test/suite/tianmu/r/issue1848.result
  mysql-test/suite/tianmu/t/issue1848.test
  storage/tianmu/common/common_definitions.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/core/table_share.cpp
  storage/tianmu/core/temp_table.cpp
  storage/tianmu/core/temp_table.h
  storage/tianmu/core/tianmu_table.cpp
  storage/tianmu/data/pack_int.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/optimizer/aggregation_algorithm.cpp
  storage/tianmu/optimizer/aggregator_advanced.cpp
  storage/tianmu/optimizer/aggregator_advanced.h
  storage/tianmu/optimizer/compile/compiled_query.cpp
  storage/tianmu/optimizer/compile/compiled_query.h
  storage/tianmu/optimizer/group_table.cpp
  storage/tianmu/optimizer/group_table.h
  storage/tianmu/optimizer/groupby_wrapper.cpp
  storage/tianmu/optimizer/groupby_wrapper.h
  storage/tianmu/system/file_system.cpp
Labels: PR-bug

#1856 fix(tianmu): To fixup the instance crashed if the result of aggregate is out of boundary
  mysql-test/suite/tianmu/r/issue1855.result
  mysql-test/suite/tianmu/t/issue1855.test
  storage/tianmu/core/value_or_null.cpp
  storage/tianmu/core/value_or_null.h
  storage/tianmu/data/pack_int.cpp
Labels: PR-bug

#1867 fix(tianmu): Fixup the mem leakage of aggregation function
  mysql-test/suite/tianmu/r/issue1855.result
  mysql-test/suite/tianmu/t/issue1855.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/just_a_table.cpp
  storage/tianmu/core/query.cpp
  storage/tianmu/core/value_or_null.cpp
  storage/tianmu/core/value_or_null.h
  storage/tianmu/vc/expr_column.cpp
Labels: PR-bug

#1881 fix(tianmu): fix UNION of non-matching columns and express with aggregation (#1861 #1864 #1873 #1870)
  mysql-test/suite/tianmu/r/issue1784.result
  mysql-test/suite/tianmu/r/issue1864.result
  mysql-test/suite/tianmu/r/various_join.result
  mysql-test/suite/tianmu/t/issue1784.test
  mysql-test/suite/tianmu/t/issue1864.test
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/core/temp_table.cpp
  storage/tianmu/optimizer/aggregation_algorithm.cpp
Labels: PR-bug

#1886 test(tianmu): add order by sentence in the mtr case various_join.test
  mysql-test/suite/tianmu/r/various_join.result
  mysql-test/suite/tianmu/t/various_join.test
Labels: PR-testing

#1888 test(mtr): add more test cases for tianmu(#1196)
  mysql-test/suite/tianmu/r/case_when.result
  mysql-test/suite/tianmu/r/drop_restric.result
  mysql-test/suite/tianmu/r/empty_string_not_null.result
  mysql-test/suite/tianmu/r/left_right_func.result
  mysql-test/suite/tianmu/r/like_not_like.result
  mysql-test/suite/tianmu/r/multi_join.result
  mysql-test/suite/tianmu/r/order_by.result
  mysql-test/suite/tianmu/r/ssb_small.result
  mysql-test/suite/tianmu/r/union_case.result
  mysql-test/suite/tianmu/t/case_when.test
  mysql-test/suite/tianmu/t/drop_restric.test
  mysql-test/suite/tianmu/t/empty_string_not_null.test
  mysql-test/suite/tianmu/t/left_right_func.test
  mysql-test/suite/tianmu/t/like_not_like.test
  mysql-test/suite/tianmu/t/multi_join.test
  mysql-test/suite/tianmu/t/order_by.test
  mysql-test/suite/tianmu/t/ssb_small.test
  mysql-test/suite/tianmu/t/union_case.test
Labels: PR-testing

#1891 test(mtr): add order by sentence in the mtr case various_join.test
  mysql-test/suite/tianmu/r/various_join.result
  mysql-test/suite/tianmu/t/various_join.test
Labels: PR-testing

#1884 fix(tianmu): To suuport ignore option for update statement
  mysql-test/suite/tianmu/r/issue1616.result
  mysql-test/suite/tianmu/t/issue1616.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/table_share.cpp
  storage/tianmu/core/table_share.h
  storage/tianmu/core/tianmu_table.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/handler/ha_tianmu.h
  storage/tianmu/index/tianmu_table_index.cpp
  storage/tianmu/index/tianmu_table_index.h
  storage/tianmu/vc/tianmu_attr.cpp
  storage/tianmu/vc/tianmu_attr.h
Labels: PR-bug

#1901 docs(intro): update the support for 8.0
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/intro.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/00-about-stonedb/limits.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/09-FAQ/stonedb-faq.md
Labels: PR-docs

#1905 workflow(codecov): Filter out excess code files
  .github/workflows/pull_requests.yml
  codecov.yml
Labels: PR-testing

#1909 workflow(coverage): Update the lcov running logic(#1908)(##1592)
  .github/workflows/pull_requests.yml
Labels: A-github

#1896 fix(tianmu): default value of the field take unaffect in load #1865
  mysql-test/suite/tianmu/r/issue1865.result
  mysql-test/suite/tianmu/std_data/issue1865.dat
  mysql-test/suite/tianmu/t/issue1865.test
  storage/tianmu/loader/parsing_strategy.cpp
Labels: PR-bug

#1887 fix(tianmu): To support union(all) the statement which is without from clause
  mysql-test/suite/tianmu/r/issue1860.result
  mysql-test/suite/tianmu/t/issue1860.test
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/just_a_table.h
  storage/tianmu/core/query.cpp
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/core/temp_table.cpp
  storage/tianmu/core/temp_table.h
  storage/tianmu/core/temp_table_com.cpp
  storage/tianmu/core/temp_table_low.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/index/multi_index.cpp
  storage/tianmu/index/multi_index.h
  storage/tianmu/optimizer/compile/compiled_query.cpp
  storage/tianmu/optimizer/compile/compiled_query.h
  storage/tianmu/sql/ha_my_tianmu.cpp
  storage/tianmu/sql/ha_my_tianmu.h
  storage/tianmu/vc/column_bin_encoder.cpp
Labels: PR-bug

#1911 fix(tianmu): To remove unnessary optimization in tianmu
  mysql-test/suite/tianmu/r/alter_table1.result
  mysql-test/suite/tianmu/r/issue1861.result
  mysql-test/suite/tianmu/r/issue1865.result
  mysql-test/suite/tianmu/r/issue848.result
  mysql-test/suite/tianmu/t/alter_table1.test
  mysql-test/suite/tianmu/t/issue1523.test
  mysql-test/suite/tianmu/t/issue1861.test
  mysql-test/suite/tianmu/t/issue1865.test
  mysql-test/suite/tianmu/t/issue848.test
  storage/tianmu/core/query_compile.cpp
Labels: PR-bug

#1869 fix(tianmu): hotfix corruption in ValueOrNull under multi-thread
  mysql-test/suite/tianmu/r/issue1855.result
  mysql-test/suite/tianmu/t/issue1855.test
  storage/tianmu/core/value_or_null.cpp
  storage/tianmu/core/value_or_null.h
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/optimizer/aggregation_algorithm.cpp
  storage/tianmu/optimizer/aggregator_basic.cpp
  storage/tianmu/optimizer/aggregator_basic.h
  storage/tianmu/optimizer/group_table.cpp
  storage/tianmu/vc/column_share.h
  storage/tianmu/vc/expr_column.cpp
Labels: PR-bug

#1902 fix(tianmu): incorrect result when using where expr and args > bigint_max #1564
  mysql-test/suite/tianmu/r/issue1564.result
  mysql-test/suite/tianmu/t/issue1564.test
  storage/tianmu/core/mysql_expression.cpp
  storage/tianmu/core/value_or_null.cpp
  storage/tianmu/core/value_or_null.h
  storage/tianmu/optimizer/condition_encoder.cpp
  storage/tianmu/types/tianmu_num.cpp
  storage/tianmu/types/tianmu_num.h
  storage/tianmu/vc/const_column.h
  storage/tianmu/vc/const_expr_column.h
  storage/tianmu/vc/expr_column.h
  storage/tianmu/vc/multi_value_column.h
  storage/tianmu/vc/single_column.h
  storage/tianmu/vc/tianmu_attr.h
  storage/tianmu/vc/tianmu_attr_exeq_rs.cpp
  storage/tianmu/vc/type_cast_column.h
  storage/tianmu/vc/virtual_column_base.h
Labels: PR-bug

#1895 fix(tianmu): add TIME_to_ulonglong_time_round process and fix up precision loss problem (#1173)
  mysql-test/suite/tianmu/r/issue1173.result
  mysql-test/suite/tianmu/t/issue1173.test
  storage/tianmu/core/item_tianmu_field.cpp
  storage/tianmu/core/tianmu_table.cpp
Labels: PR-bug

#1906 fix(sql,tianmu):fix when binlog format is row, the load data statement cannot be recorded(#1876)
  mysql-test/suite/tianmu/r/issue1876.result
  mysql-test/suite/tianmu/t/issue1876-master.opt
  mysql-test/suite/tianmu/t/issue1876.test
  sql/binlog.cc
  sql/sql_class.h
  storage/tianmu/core/tianmu_table.cpp
  storage/tianmu/core/tianmu_table.h
  storage/tianmu/loader/load_parser.cpp
Labels: PR-bug
