Repository stoneatom/stonedb, pull requests merged in 2023-01, with the labels that each got.

#1178 fix(tianmu):Master slave synchronization, primary key scanning failed(#1174)
  mysql-test/suite/tianmu/r/issue1174.result
  mysql-test/suite/tianmu/t/issue1174.test
  storage/tianmu/handler/ha_tianmu.cpp
Labels: A-bug, PR-bug

#1171 fix(tianmu): When executing SELECT..WHERE NAME LIKE %_, it failed(#1157)
  mysql-test/suite/tianmu/r/issue1157.result
  mysql-test/suite/tianmu/t/issue1157.test
  storage/tianmu/core/tianmu_attr_exqp.cpp
Labels: PR-bug

#1184 feat(tianmu): tianmu exporter support NULL type. (#1169)
  mysql-test/suite/tianmu/r/issue1169.result
  mysql-test/suite/tianmu/std_data/issue1169.txt
  mysql-test/suite/tianmu/std_data/issue1169_out_1.txt
  mysql-test/suite/tianmu/std_data/issue1169_out_2.txt
  mysql-test/suite/tianmu/t/issue1169.test
  storage/tianmu/core/engine.h
  storage/tianmu/exporter/data_exporter_txt.cpp
  storage/tianmu/exporter/data_exporter_txt.h
  storage/tianmu/loader/parsing_strategy.cpp
Labels: PR-feature

#1200 fix: fix incorrect result when executed insert into t select with ... #1182
  mysql-test/suite/tianmu/r/bit_type.result
  mysql-test/suite/tianmu/r/primary_secondary_bit.result
  mysql-test/suite/tianmu/t/bit_type.test
  mysql-test/suite/tianmu/t/primary_secondary_bit.test
  storage/tianmu/core/engine_convert.cpp
Labels: PR-bug

#1195 test(mtr): add some mtr test cases(#497)
  mysql-test/suite/tianmu/r/escape.result
  mysql-test/suite/tianmu/r/replace_into.result
  mysql-test/suite/tianmu/r/unsigned.result
  mysql-test/suite/tianmu/r/unsigned_greatest.result
  mysql-test/suite/tianmu/r/unsigned_math.result
  mysql-test/suite/tianmu/r/zerofill.result
  mysql-test/suite/tianmu/t/escape.test
  mysql-test/suite/tianmu/t/replace_into.test
  mysql-test/suite/tianmu/t/unsigned.test
  mysql-test/suite/tianmu/t/unsigned_greatest.test
  mysql-test/suite/tianmu/t/unsigned_math.test
  mysql-test/suite/tianmu/t/zerofill.test
Labels: PR-testing

#1220 fix: insert with unsigned data return out of range, but still being queried #1218
  mysql-test/suite/tianmu/r/out_of_range_issue1151.result
  mysql-test/suite/tianmu/t/out_of_range_issue1151.test
  storage/tianmu/common/common_definitions.cpp
Labels: PR-bug

#1233 fix(tianmu): tianmu.primary_secondary_bit crashed or failed(#1212)
  sql/log_event_push_cond.cc
Labels: A-bug, PR-bug

#1239 fix(website): fix the compile error(#1238)
  Docs/download.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/download.md
Labels: PR-bug, PR-docs

#1240 fix(website): delete the error tags and update docs(#1238)
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-redhat7/compile-using-redhat7-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/download.md
Labels: PR-bug, PR-docs

#1250 fix: mirros pull failed in debian10_1.0.3 #1249
  .github/workflows/pull_requests.yml
Labels: PR-bug

#1256 fix(website): Fixed the Roadmap module(#1255)
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/deploy-stonedb-with-deb.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/deploy-stonedb-with-tar.md
  website/i18n/zh/docusaurus-plugin-content-pages/index.md
  website/src/components/roadMap/step/index.tsx
  website/src/components/roadMap/step/styles.ts
Labels: PR-bug, PR-docs

#1257 test(mtr): add testcases for bit and unsigned(#1196)
  mysql-test/suite/tianmu/r/alter_bit.result
  mysql-test/suite/tianmu/r/bit.result
  mysql-test/suite/tianmu/r/func_bit.result
  mysql-test/suite/tianmu/r/other_bit.result
  mysql-test/suite/tianmu/r/unsigned_join.result
  mysql-test/suite/tianmu/std_data/1m_customer.tbl
  mysql-test/suite/tianmu/std_data/1m_orders.tbl
  mysql-test/suite/tianmu/t/alter_bit.test
  mysql-test/suite/tianmu/t/bit.test
  mysql-test/suite/tianmu/t/func_bit.test
  mysql-test/suite/tianmu/t/other_bit.test
  mysql-test/suite/tianmu/t/unsigned_join.test
Labels: PR-testing

#1252 feat(stonedb): show stonedb tag version. (#1251)
  CMakeLists.txt
  mysql-test/suite/tianmu/r/issue1251.result
  mysql-test/suite/tianmu/t/issue1251.test
  sql/build_info.h.ini
  sql/build_info_t.h
  sql/mysqld.cc
Labels: PR-feature

#1259 fix: docs some minors in README
  README_zh-hans.md
Labels: PR-bug
