Repository stoneatom/stonedb, pull requests merged in 2023-04, with the labels that each got.

#1490 fix(tianmu): backport fix temporary tables are not available#1413
  mysql-test/suite/tianmu/t/issue441.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/index/rdb_utils.h
Labels: PR-bug

#1491 fix(tianmu):backport date functions used in where statement, query result is empty#1432
  mysql-test/suite/tianmu/r/issue496.result
  mysql-test/suite/tianmu/r/issue566.result
  mysql-test/suite/tianmu/t/issue496.test
  mysql-test/suite/tianmu/t/issue566.test
  storage/tianmu/types/rc_datetime.cpp
  storage/tianmu/types/value_parser4txt.cpp
Labels: PR-bug

#1488 feat(unittest): add unittest module, impl gtestmock #1416
  storage/tianmu/CMakeLists.txt
  storage/tianmu/unittest/CMakeLists.txt
  storage/tianmu/unittest/testgmock.cpp
Labels: PR-feature

#1521 feat(core): support row formate on master-replica for tianmu engine #1409
  mysql-test/include/default_mysqld.cnf
  mysql-test/suite/tianmu/r/alter_table_v1.result
  mysql-test/suite/tianmu/r/insert_select.result
  mysql-test/suite/tianmu/r/issue364.result
  mysql-test/suite/tianmu/r/issue496.result
  mysql-test/suite/tianmu/r/issue723-1.result
  mysql-test/suite/tianmu/r/issue723-2.result
  mysql-test/suite/tianmu/r/primary_secondary_issue1409.result
  mysql-test/suite/tianmu/t/disabled.def
  mysql-test/suite/tianmu/t/issue496.test
  mysql-test/suite/tianmu/t/issue723-2.test
  mysql-test/suite/tianmu/t/primary_secondary_issue1409.test
  storage/tianmu/handler/ha_tianmu.h
Labels: PR-feature

#1484 fix(core): Query results more data with filter and & or #1435
  mysql-test/suite/tianmu/r/issue282.result
  mysql-test/suite/tianmu/t/issue282.test
  storage/tianmu/core/query.cpp
Labels: PR-bug

#1522 style(execution): improve code readability (#1422)
  mysql-test/suite/tianmu/r/issue228.result
  mysql-test/suite/tianmu/t/issue228.test
  storage/tianmu/core/query.cpp
Labels: PR-style

#1512 feat(tianmu): phase2, impl delete in tianmu #702
  mysql-test/suite/tianmu/r/delete.result
  mysql-test/suite/tianmu/t/delete.test
  storage/tianmu/common/defs.h
  storage/tianmu/core/column_share.cpp
  storage/tianmu/core/column_share.h
  storage/tianmu/core/dpn.h
  storage/tianmu/core/pack.cpp
  storage/tianmu/core/pack.h
  storage/tianmu/core/pack_int.cpp
  storage/tianmu/core/pack_int.h
  storage/tianmu/core/pack_str.cpp
  storage/tianmu/core/pack_str.h
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/core/parameterized_filter.h
  storage/tianmu/core/rc_attr.cpp
  storage/tianmu/core/rc_attr.h
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/core/rc_table.h
  storage/tianmu/core/rcattr_exqp.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/index/rc_table_index.cpp
  storage/tianmu/index/rc_table_index.h
Labels: PR-feature

#1531 fix(workflow): remove dup lines in git workflow(#1517)
  .github/workflows/nightly.yml
  .github/workflows/pull_requests.yml
Labels: PR-bug

#1526 fix(core): fix insert failed when table name has special character #1412
  mysql-test/suite/tianmu/t/issue222-master.opt
  mysql-test/suite/tianmu/t/issue222.test
  mysql-test/suite/tianmu/t/issue362-master.opt
  mysql-test/suite/tianmu/t/issue362.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
Labels: PR-bug

#1524 fix(tianmu):The myloader cann't work if the autocommit is closed. (#1510)
  mysql-test/suite/tianmu/r/double_float.result
  mysql-test/suite/tianmu/r/issue1510.result
  mysql-test/suite/tianmu/t/double_float.test
  mysql-test/suite/tianmu/t/issue1510-master.opt
  mysql-test/suite/tianmu/t/issue1510.test
  storage/tianmu/core/engine.cpp
Labels: PR-bug

#1528 fix(core): fix bug: The instance occasionally crashes if both fields …
  mysql-test/suite/tianmu/r/hash_join.result
  mysql-test/suite/tianmu/t/hash_join.test
  storage/tianmu/core/parallel_hash_join.cpp
Labels: PR-bug

#1535 fix: page hover font style
  website/src/css/custom.less
Labels: PR-bug

#1537 feat(mtr): To fix the mtr usage
  mysql-test/suite/tianmu/t/auto_increment.test
  mysql-test/suite/tianmu/t/disabled.def
  mysql-test/suite/tianmu/t/issue364.test
  mysql-test/suite/tianmu/t/issue433.test
  mysql-test/suite/tianmu/t/issue446.test
  mysql-test/suite/tianmu/t/issue581.test
  mysql-test/suite/tianmu/t/load.test
  mysql-test/suite/tianmu/t/trigger.test
Labels: PR-feature

#1541 fix(optmizer):fix the crashes when the right table of hash join is in parallel(#1538)
  mysql-test/suite/tianmu/r/hash_join.result
  mysql-test/suite/tianmu/t/hash_join.test
  storage/tianmu/core/parallel_hash_join.cpp
Labels: PR-bug

#1530 fix(tianmu): fix specified key was too long; max key length is 255 (#1417)
  mysql-test/suite/tianmu/r/issue228.result
  mysql-test/suite/tianmu/t/issue228.test
  storage/tianmu/common/common_definitions.h
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/handler/ha_tianmu.h
  storage/tianmu/system/configuration.cpp
  storage/tianmu/system/configuration.h
Labels: PR-bug

#1548 fix(website): fix website error #1449
  Docs/02-getting-started/quick-add-mtr-test.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu2204-for-80.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-add-mtr-test.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu2204-for-80.md
Labels: PR-bug

#1546 feat(tianmu): support volcano framewrok
  storage/tianmu/core/delta_table.cpp
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/tianmu_table.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/index/kv_store.cpp
  storage/tianmu/index/kv_store.h
  storage/tianmu/index/kv_transaction.cpp
  storage/tianmu/index/tianmu_table_index.cpp
  storage/tianmu/system/tianmu_system.cpp
  storage/tianmu/system/tianmu_system.h
Labels: PR-feature

#1544 feat(tianmu): support delete from tbl, delete t1, t2 from tbl_ref where #702
  mysql-test/suite/tianmu/r/delete_all_rows.result
  mysql-test/suite/tianmu/r/issue663.result
  mysql-test/suite/tianmu/t/delete.test
  mysql-test/suite/tianmu/t/delete_all_rows.test
  mysql-test/suite/tianmu/t/issue663.test
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/upgrade/README.md
Labels: PR-feature

#1555 fix(tianmu): revert code, mv ret value from try block back to catch block. (#1532)
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1533 feat(tiamnu): hard code in defs.h (#1481)
  storage/tianmu/common/defs.h
  storage/tianmu/core/table_share.h
  storage/tianmu/vc/column_share.cpp
  storage/tianmu/vc/column_share.h
  storage/tianmu/vc/tianmu_attr.cpp
Labels: PR-feature

#1565 docs:update the compile guides #1562
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004/compile-using-ubuntu2004-for-56.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004/compile-using-ubuntu2004-for-57.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu2204-for-80.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004/compile-using-ubuntu2004-for-56.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2004/compile-using-ubuntu2004-for-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu2204-for-80.md
Labels: PR-docs

#1566 feat(tianmu):set system variable "tianmu_large_prefix" default value from OFF to ON. #1426
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#1558 fix(tianmu):remove the warnings when compiling stonedb-8.0-dev(#1556)
  storage/tianmu/core/group_distinct_table.cpp
  storage/tianmu/core/mi_new_contents.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/index/rc_table_index.cpp
  storage/tianmu/index/rdb_meta_manager.cpp
Labels: PR-bug

#1570 feat(tianmu): support select ... from t left join (nested join) on cond #1560
  mysql-test/suite/tianmu/r/issue1560.result
  mysql-test/suite/tianmu/r/issue282.result
  mysql-test/suite/tianmu/t/issue1560.test
  sql/sql_optimizer.cc
  storage/tianmu/core/query_compile.cpp
Labels: PR-feature

#1547 fix(tianmu):Remove excess log printing and add some code comments(#1545)
  storage/tianmu/executor/combined_iterator.cpp
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1573 fix(tianmu):the instance crashed while using derived table(#1439)
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1578 fix(core): results uncorrect caused by exists subquery #1428
  storage/tianmu/core/dimension_group.cpp
  storage/tianmu/core/multi_index.cpp
  storage/tianmu/core/multi_index.h
Labels: PR-bug

#1576 fix(tianmu): fix crashed & make exception more friendly #1438
  storage/tianmu/common/exception.cpp
  storage/tianmu/common/exception.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.ic
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/core/rcattr_exqp.cpp
Labels: PR-bug

#1582 fix(tianmu): fix mysqld crash when exec query with AggregateRough, assert failed on i < m_idx.size() at tianmu_attr.h:387, msg: [bad dpn index 0/0] (#1580)
  storage/tianmu/vc/tianmu_attr.cpp
Labels: PR-bug

#1579 test(mtr):standardize tianmu testcases.(#1574)
  mysql-test/suite/tianmu/r/add_column.result
  mysql-test/suite/tianmu/r/dropdb.result
  mysql-test/suite/tianmu/r/issue222.result
  mysql-test/suite/tianmu/r/issue226.result
  mysql-test/suite/tianmu/r/issue281.result
  mysql-test/suite/tianmu/r/issue282.result
  mysql-test/suite/tianmu/r/issue342.result
  mysql-test/suite/tianmu/r/issue362.result
  mysql-test/suite/tianmu/r/issue364.result
  mysql-test/suite/tianmu/r/issue405.result
  mysql-test/suite/tianmu/r/issue410.result
  mysql-test/suite/tianmu/r/issue417.result
  mysql-test/suite/tianmu/r/issue429.result
  mysql-test/suite/tianmu/r/issue430.result
  mysql-test/suite/tianmu/r/issue431.result
  mysql-test/suite/tianmu/r/issue441.result
  mysql-test/suite/tianmu/r/issue464.result
  mysql-test/suite/tianmu/r/issue467.result
  mysql-test/suite/tianmu/r/issue468.result
  mysql-test/suite/tianmu/r/issue469.result
  mysql-test/suite/tianmu/r/issue475.result
  mysql-test/suite/tianmu/r/issue502.result
  mysql-test/suite/tianmu/r/issue515.result
  mysql-test/suite/tianmu/r/issue736.result
  mysql-test/suite/tianmu/r/issue767.result
  mysql-test/suite/tianmu/r/issues_tx417.result
  mysql-test/suite/tianmu/r/lz4.result
  mysql-test/suite/tianmu/r/orquery.result
  mysql-test/suite/tianmu/r/orquery1.result
  mysql-test/suite/tianmu/t/add_column.test
  mysql-test/suite/tianmu/t/dropdb.test
  mysql-test/suite/tianmu/t/group_concat.test
  mysql-test/suite/tianmu/t/group_concat2.test
  mysql-test/suite/tianmu/t/issue222.test
  mysql-test/suite/tianmu/t/issue226.test
  mysql-test/suite/tianmu/t/issue281.test
  mysql-test/suite/tianmu/t/issue282.test
  mysql-test/suite/tianmu/t/issue342.test
  mysql-test/suite/tianmu/t/issue362.test
  mysql-test/suite/tianmu/t/issue364.test
  mysql-test/suite/tianmu/t/issue405.test
  mysql-test/suite/tianmu/t/issue410.test
  mysql-test/suite/tianmu/t/issue417.test
  mysql-test/suite/tianmu/t/issue429.test
  mysql-test/suite/tianmu/t/issue430.test
  mysql-test/suite/tianmu/t/issue431.test
  mysql-test/suite/tianmu/t/issue441.test
  mysql-test/suite/tianmu/t/issue464.test
  mysql-test/suite/tianmu/t/issue467.test
  mysql-test/suite/tianmu/t/issue468.test
  mysql-test/suite/tianmu/t/issue469.test
  mysql-test/suite/tianmu/t/issue475.test
  mysql-test/suite/tianmu/t/issue502.test
  mysql-test/suite/tianmu/t/issue515.test
  mysql-test/suite/tianmu/t/issue736.test
  mysql-test/suite/tianmu/t/issue767.test
  mysql-test/suite/tianmu/t/issues_tx417.test
  mysql-test/suite/tianmu/t/lz4.test
  mysql-test/suite/tianmu/t/orquery.test
  mysql-test/suite/tianmu/t/orquery1.test
Labels: PR-testing

#1554 feat(tianmu): support volcano framework
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/parallel_hash_join.cpp
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/core/temp_table_low.cpp
  storage/tianmu/core/tianmu_table.cpp
  storage/tianmu/executor/task_executor.cpp
  storage/tianmu/exporter/data_exporter.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/loader/load_parser.cpp
  storage/tianmu/mm/traceable_object.cpp
  storage/tianmu/optimizer/aggregation_algorithm.cpp
  storage/tianmu/optimizer/compile/descriptor.cpp
  storage/tianmu/optimizer/joiner_general.cpp
  storage/tianmu/optimizer/joiner_mapped.cpp
  storage/tianmu/sql/ha_my_tianmu.cpp
  storage/tianmu/system/tianmu_system.cpp
  storage/tianmu/system/tianmu_system.h
  storage/tianmu/util/sorter_wrapper.cpp
  storage/tianmu/vc/column_share.cpp
  storage/tianmu/vc/tianmu_attr.cpp
  storage/tianmu/vc/tianmu_attr_exqp.cpp
Labels: PR-feature

#1594 feat(mtr): add select & insert test cases #1420
  mysql-test/suite/tianmu/r/insert.result
  mysql-test/suite/tianmu/r/issue1560.result
  mysql-test/suite/tianmu/r/issue415.result
  mysql-test/suite/tianmu/r/select.result
  mysql-test/suite/tianmu/t/insert.test
  mysql-test/suite/tianmu/t/issue1560.test
  mysql-test/suite/tianmu/t/issue415.testbak
  mysql-test/suite/tianmu/t/select.test
Labels: PR-feature

#1600 fix: max-width navbar search style
  website/src/css/custom.less
Labels: PR-bug, PR-docs, PR-improvement

#1607 backport:fix assert failed on i < m_idx.size().(#1444)
  storage/tianmu/core/parameterized_filter.cpp
  storage/tianmu/core/parameterized_filter.h
Labels: PR-bug, C-stonedb-8.0, A-porting

#1602 fix(tianmu):The rows in the test result is incorrect.(#1431)
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1626 fix(core): crashed happened when execute delete t from ... where (sub…
  mysql-test/suite/tianmu/t/delete.test
  storage/tianmu/core/query_compile.cpp
Labels: PR-bug

#1631 fix(core): fix bug caused by concatenated calls of multiple triggers #1434
  mysql-test/suite/tianmu/r/trigger.result
  mysql-test/suite/tianmu/t/trigger.test
  sql/handler.cc
  sql/sql_delete.cc
Labels: PR-bug

#1633 feat(mtr): modify insert_update.test and update_v1.test(#1420)
  mysql-test/suite/tianmu/r/insert_update.result
  mysql-test/suite/tianmu/r/update_v1.result
  mysql-test/suite/tianmu/t/insert_update.test
  mysql-test/suite/tianmu/t/update_v1.test
Labels: PR-feature

#1636 feat(mtr): pick up some cases cannot pass before (#1420)
  mysql-test/suite/tianmu/r/create_table.result
  mysql-test/suite/tianmu/r/delete.result
  mysql-test/suite/tianmu/r/delete_all_rows.result
  mysql-test/suite/tianmu/t/create_table.test
  mysql-test/suite/tianmu/t/delete.test
  mysql-test/suite/tianmu/t/delete_all_rows.test
Labels: PR-feature

#1642 fix(tianmu): fix MySQL server has gone away when exec query (#1641 #1640)
  sql/sql_optimizer.cc
  storage/tianmu/core/engine_execute.cpp
Labels: PR-bug
