Repository stoneatom/stonedb, pull requests merged in 2023-02, with the labels that each got.

#1261 feat(scripts): change default binlog format from statement to row in my.cnf.sample #1015
  scripts/my.cnf.sample
Labels: PR-feature

#1269 fix(stonedb): fix 'STONEDB_TAG_NAME' complier error. (#1262)
  .github/workflows/pull_requests.yml
Labels: PR-bug

#1244 feat(tianmu):Master-slave synchronization, bit type supported by conditional push (#1230)
  sql/log_event_push_cond.cc
Labels: A-feature

#1283 docs(quick-deployment): update the link of quick-deployment(#1282)
  Docs/02-getting-started/quick-deployment-of-stonedb-as-the-secondary-database.md
  Docs/02-getting-started/quick-deployment/deploy-stonedb-with-deb.md
  Docs/02-getting-started/quick-deployment/deploy-stonedb-with-tar.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment-of-stonedb-as-the-secondary-database.md
Labels: PR-docs

#1287 fix action ssl build error
  .github/workflows/pull_requests.yml
Labels: PR-bug

#1268 fix(load): fix mysqld crash when loaded data column contains double enclosed char. (#1263)
  mysql-test/suite/tianmu/r/issue1263.result
  mysql-test/suite/tianmu/std_data/issue1263-1.txt
  mysql-test/suite/tianmu/std_data/issue1263-2.txt
  mysql-test/suite/tianmu/std_data/issue1263-3.txt
  mysql-test/suite/tianmu/t/issue1263.test
  storage/tianmu/loader/load_parser.cpp
  storage/tianmu/loader/parsing_strategy.cpp
Labels: PR-bug

#1279 feat(tianmu): add multi-thread aggregation of group by (#422)
  mysql-test/include/default_mysqld.cnf
  mysql-test/suite/tianmu/r/issue422.result
  mysql-test/suite/tianmu/r/issue790.result
  mysql-test/suite/tianmu/r/out_of_range_issue1151.result
  mysql-test/suite/tianmu/r/select_joins.result
  mysql-test/suite/tianmu/t/issue422.test
  mysql-test/suite/tianmu/t/out_of_range_issue1151.test
  scripts/my.cnf.sample
  storage/tianmu/core/aggregation_algorithm.cpp
  storage/tianmu/core/aggregation_algorithm.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/pack_guardian.cpp
  storage/tianmu/core/pack_guardian.h
  storage/tianmu/core/temp_table.cpp
  storage/tianmu/core/tianmu_attr.cpp
  storage/tianmu/core/value_or_null.cpp
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/system/configuration.cpp
  storage/tianmu/system/configuration.h
Labels: PR-feature

#1298 test(mtr): optimize func_sec_to_time.test(#1196)
  mysql-test/suite/tianmu/r/alter_table_v1.result
  mysql-test/suite/tianmu/r/func_sec_to_time.result
  mysql-test/suite/tianmu/t/alter_table_v1.test
  mysql-test/suite/tianmu/t/func_sec_to_time.test
Labels: PR-testing

#1235 fix(tianmu): fix alter table add column not null.(#1188)
  mysql-test/suite/tianmu/r/alter_column.result
  mysql-test/suite/tianmu/t/alter_column.test
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/handler/ha_tianmu.h
Labels: PR-bug

#1307 feat(scripts): check version of the compilation tools before build(#1295)
  scripts/stonedb_build.sh
Labels: PR-feature

#1281 bug(tianmu):improve the code quality and refactoring derived table optimize for tianmu(#1277, #1276, #1258)
  mysql-test/suite/tianmu/r/issue1258.result
  mysql-test/suite/tianmu/t/issue1258.test
  sql/sql_derived.cc
  sql/sql_lex.h
  sql/sql_optimizer.cc
  sql/sql_optimizer.h
  sql/sql_parse.cc
  sql/sql_select.cc
  sql/sql_select.h
  sql/table.h
  storage/tianmu/core/engine.h
  storage/tianmu/core/engine_execute.cpp
  storage/tianmu/core/query_compile.cpp
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_my_tianmu.h
Labels: PR-bug

#1272 fix(tianmu):the data is wrong when altering table after deleting.(#1199)
  mysql-test/suite/tianmu/r/alter_delete.result
  mysql-test/suite/tianmu/t/alter_delete.test
  storage/tianmu/core/dimension_group.cpp
  storage/tianmu/core/tianmu_table.h
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1314 fix(tianmu):issue1090.test occasionally fails to run(#1234)
  mysql-test/suite/tianmu/r/issue1090.result
  mysql-test/suite/tianmu/t/issue1090.test
Labels: PR-bug

#1297 fix(tianmu):the data is wrong when updating data after atlering table.(#1253)
  mysql-test/suite/tianmu/r/alter_update.result
  mysql-test/suite/tianmu/t/alter_update.test
  storage/tianmu/core/mysql_expression.cpp
  storage/tianmu/core/pack_int.cpp
  storage/tianmu/core/pack_str.cpp
Labels: PR-bug

#1273 feat(tianmu): support in-completed column data during load data. (#1209)
  mysql-test/suite/tianmu/r/issue1209.result
  mysql-test/suite/tianmu/r/issue1263.result
  mysql-test/suite/tianmu/std_data/issue1209-1.txt
  mysql-test/suite/tianmu/std_data/issue1209-2.txt
  mysql-test/suite/tianmu/t/issue1209.test
  mysql-test/suite/tianmu/t/issue1263.test
  storage/tianmu/loader/load_parser.cpp
  storage/tianmu/loader/parsing_strategy.cpp
  storage/tianmu/loader/parsing_strategy.h
Labels: PR-feature

#1315 feat(tianmu):add some feature of init auto_increment_value for tianmu(#1201, #1072, #1059)
  mysql-test/suite/tianmu/r/init_auto_increment_value.result
  mysql-test/suite/tianmu/std_data/load_auto_increment_value.txt
  mysql-test/suite/tianmu/t/init_auto_increment_value.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/filter.cpp
  storage/tianmu/core/table_share.cpp
  storage/tianmu/core/tianmu_attr.cpp
  storage/tianmu/core/tianmu_attr.h
  storage/tianmu/core/tianmu_table.cpp
  storage/tianmu/core/tianmu_table.h
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#1321 bug(tianmu):Server crashed, when execute select val, val >= '2010-02-22 18:35:23' from (select * from timetest) as A; (#981)
  mysql-test/suite/tianmu/r/issue981.result
  mysql-test/suite/tianmu/t/issue981.test
  sql/protocol_classic.cc
Labels: PR-bug
