Repository stoneatom/stonedb, pull requests merged in 2023-05, with the labels that each got.

#1643 fix(tianmu):Support insert ignore syntax (#1637)
  mysql-test/suite/tianmu/r/issue1637.result
  mysql-test/suite/tianmu/t/issue1637-master.opt
  mysql-test/suite/tianmu/t/issue1637.test
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/tianmu_table.cpp
  storage/tianmu/core/tianmu_table.h
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1660 fix(tianmu): fix query input variables wrong result (#1647)
  storage/tianmu/vc/expr_column.cpp
Labels: PR-bug

#1663 fix(tianmu):mysqld crash when select from multitable #1657
  mysql-test/suite/tianmu/r/delete.result
  mysql-test/suite/tianmu/t/delete.test
  storage/tianmu/core/multi_index.cpp
Labels: PR-bug

#1688 fix(tianmu): fix result of the query using the subquery derived table is incorrect (#1662)
  mysql-test/suite/tianmu/r/issue1662.result
  mysql-test/suite/tianmu/t/issue1662.test
  storage/tianmu/core/engine_execute.cpp
Labels: PR-bug

#1656 fix(workflows): fix install lcov in image ubuntu2004_1.0.1.(#1651)
  .github/workflows/pull_requests.yml
Labels: PR-bug

#1697 fix(tianmu): fix results of two queries using a derived table and a custom face change are incorrect (#1696)
  mysql-test/suite/tianmu/r/issue1696.test
  mysql-test/suite/tianmu/t/issue1696.test
  storage/tianmu/core/engine_execute.cpp
Labels: PR-bug

#1705 feat(tianmu): Test cases that supplement custom variables (#1703)
  mysql-test/suite/tianmu/r/issue1696.result
  mysql-test/suite/tianmu/r/issue1696.test
  mysql-test/suite/tianmu/t/issue1696.test
Labels: PR-feature

#1744 fix(tianmu): fix mysqld crash when assigning return values using both custom variables and derived tables (#1707)
  mysql-test/suite/tianmu/r/issue1707.result
  mysql-test/suite/tianmu/t/issue1707.test
  sql/sql_union.cc
  storage/tianmu/core/query_compile.cpp
Labels: PR-bug

#1746 fix(tianmu): Insert ignore can insert duplicate values.(#1699)
  mysql-test/suite/tianmu/r/issue1637.result
  mysql-test/suite/tianmu/t/issue1637.test
  storage/tianmu/core/engine.cpp
Labels: PR-bug

#1749 fix(core): add mtr test issue682.test and fix crash in strict mode #1672
  mysql-test/suite/tianmu/r/issue682.result
  mysql-test/suite/tianmu/t/issue682.test
  sql/sql_delete.cc
  storage/tianmu/core/query_compile.cpp
Labels: PR-bug

#1646 feat(sql): code refactor for misleading-indentation(#1542)
  mysql-test/suite/tianmu/r/issue663.result
  sql/sql_optimizer.cc
Labels: PR-feature

#1761 test(mtr): backport delete time out #1711
  mysql-test/suite/tianmu/r/delete_all_rows.result
  mysql-test/suite/tianmu/t/delete_all_rows.test
Labels: PR-testing

#1748 fix(tianmu):backport select in date range result set incorrect #1683
  mysql-test/suite/tianmu/r/issue829.result
  mysql-test/suite/tianmu/t/issue829.test
  storage/tianmu/types/rc_datetime.cpp
Labels: PR-bug

#1758 feat(tianmu): support alter table xxx modify xxx type NULL/NOT NULL
  mysql-test/suite/tianmu/r/alter_table_null.result
  mysql-test/suite/tianmu/t/alter_table_null.test
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#1755 fix(tianmu): backport load dpn when table is empty #1684
  mysql-test/suite/tianmu/r/issue964.result
  mysql-test/suite/tianmu/t/issue964.test
  storage/tianmu/core/rc_attr.cpp
Labels: PR-bug

#1765 feat(core): support ctas #1715
  mysql-test/suite/tianmu/r/ctas.result
  mysql-test/suite/tianmu/r/issue228.result
  mysql-test/suite/tianmu/t/ctas.test
  sql/sql_cmd_ddl_table.cc
  sql/sql_select.cc
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/handler/ha_my_tianmu.cpp
  storage/tianmu/handler/ha_my_tianmu.h
Labels: PR-feature

#1766 fix(tianmu):Even if a primary key is defined, duplicate data may be imported.(#1648)
  storage/tianmu/core/tianmu_table.cpp
Labels: PR-bug

#1747 feat: add delete/drop into tianmu log stat
  storage/tianmu/core/engine.cpp
Labels: PR-feature

#1770 fix(tianmu): fix Error result set of the IN subquery with semi join (#1764)
  sql/sql_resolver.cc
Labels: PR-bug

#1745 fix(tianmu): backport query with union all result set incorrect #1681
  mysql-test/suite/tianmu/r/union.result
  mysql-test/suite/tianmu/t/union.test
  storage/tianmu/core/engine.cpp
Labels: PR-bug

#1768 doc(develop-guide): modify method for compile stonedb using docker
  Docs/04-developer-guide/00-compiling-methods/compile-using-docker.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-docker.md
Labels: PR-docs

#1782 feat(handler): mv tianmu log files back to log dir #1781
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#1771 fix: removing building warnings(#1679)
  storage/tianmu/core/parameterized_filter.cpp
Labels: PR-bug

#1772 feat(tianmu):backport support "alter table xxx comment xx"(#1694)
  mysql-test/suite/tianmu/r/alter_table_comment.result
  mysql-test/suite/tianmu/t/alter_table_comment.test
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#1783 docs: add docker compile guide of stonedb8.0.(#1780)
  Docs/04-developer-guide/00-compiling-methods/compile-using-docker/_category_.json
  Docs/04-developer-guide/00-compiling-methods/compile-using-docker/compile-using-docker-for-56-57.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-docker/compile-using-docker-for-80.md
  Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu2204-for-80.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-docker/compile-using-docker-for-56-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-docker/compile-using-docker-for-80.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu2204-for-80.md
Labels: PR-docs

#1804 fix(mtr): make sleep time longger to avoid no data select from db #1803
  mysql-test/suite/tianmu/r/issue848.result
  mysql-test/suite/tianmu/t/issue222.test
  mysql-test/suite/tianmu/t/issue362.test
  mysql-test/suite/tianmu/t/issue848.test
Labels: PR-bug

#1799 fix(tianmu): backport EXTRACT() function error stoneatom#1691
  mysql-test/suite/tianmu/r/issue845.result
  mysql-test/suite/tianmu/r/union.result
  mysql-test/suite/tianmu/t/issue845.test
  mysql-test/suite/tianmu/t/union.test
  storage/tianmu/core/mysql_expression.cpp
Labels: PR-bug

#1795 fix: remove warnings of building release type.(#1679)
  storage/tianmu/core/column_share.cpp
  storage/tianmu/system/channel.cpp
  storage/tianmu/types/rc_num.cpp
Labels: PR-bug

#1820 fix(tianmu): disable primary key as tianmu engine did not support well
  mysql-test/suite/tianmu/r/issue819.result
  mysql-test/suite/tianmu/t/issue819.test
  sql/log_event.cc
  sql/sql_insert.cc
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1825 docs(website): update the documentation for Compile StoneDB 8.0 in Docker(#1823)
  Docs/04-developer-guide/00-compiling-methods/compile-using-docker/compile-using-docker-for-80.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-docker/compile-using-docker-for-80.md
Labels: PR-docs

#1824 fix(tianmu): fix up the incompatible type
  include/mysqld_error.h
  mysql-test/suite/tianmu/r/issue1808.result
  mysql-test/suite/tianmu/t/issue1637-master.opt
  mysql-test/suite/tianmu/t/issue1637.test
  mysql-test/suite/tianmu/t/issue1808.test
  storage/tianmu/core/temp_table.cpp
Labels: PR-bug

#1841 fix(tianmu): Fix up the unknown exception after instance killed randomly
  storage/tianmu/vc/tianmu_attr.cpp
Labels: PR-bug

#1840 fix(tianmu): fix up the incorrect meta-info leads unexpected behavior
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/core/query.cpp
  storage/tianmu/core/tianmu_table.cpp
  storage/tianmu/data/dpn.h
  storage/tianmu/data/pack.h
  storage/tianmu/data/pack_guardian.cpp
  storage/tianmu/data/pack_int.cpp
  storage/tianmu/data/pack_str.cpp
  storage/tianmu/sql/ha_my_tianmu.cpp
  storage/tianmu/system/file.cpp
  storage/tianmu/system/tianmu_file.h
  storage/tianmu/vc/column_share.cpp
  storage/tianmu/vc/tianmu_attr.cpp
Labels: PR-bug

#1836 fix(workflow): nightly build failed #1830
  .github/workflows/nightly.yml
Labels: PR-bug

#1837 fix(workflow): nightly build failed #1830
  .github/workflows/nightly.yml
Labels: PR-bug

#1843 feat(tianmu): fixup the default delimeter for load data
  storage/tianmu/core/engine.cpp
  storage/tianmu/loader/parsing_strategy.cpp
Labels: PR-feature
