Repository stoneatom/stonedb, pull requests merged in 2023-03, with the labels that each got.

#1354 fix(scripts): update man pages from MySQL Server 5.7.36
  scripts/fill_help_tables.sql
Labels: PR-bug

#1353 fix(tianmu): fix endless loop occurs during data_cache (#1352)
  mysql-test/suite/tianmu/r/issue1352.result
  mysql-test/suite/tianmu/t/issue1352.test
  storage/tianmu/core/mysql_expression.cpp
Labels: PR-bug

#1341 feat(tianmu): add_timestamp_column Query result is incorrect #1327
  mysql-test/suite/tianmu/r/alter_column.result
  mysql-test/suite/tianmu/t/alter_column.test
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-feature

#1349 fix(common): limit min signed int64 value to -9223372036854775806 #1206
  mysql-test/suite/tianmu/r/signed_boundary.result
  mysql-test/suite/tianmu/t/signed_boundary.test
  storage/tianmu/common/common_definitions.cpp
Labels: PR-bug

#1351 fix(tianmu):Solve the problem that index renaming is not supported(#1345)
  mysql-test/suite/tianmu/r/issue1325.result
  mysql-test/suite/tianmu/t/issue1186-slave.opt
  mysql-test/suite/tianmu/t/issue1325.test
  sql/log_event.cc
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1357 fix(core): rm incorrect boundary check on rough check with between #1344
  mysql-test/suite/tianmu/r/signed_boundary.result
  mysql-test/suite/tianmu/t/signed_boundary.test
  storage/tianmu/core/tianmu_attr_exeq_rs.cpp
Labels: PR-bug

#1366 docs(website): Modify documentation(#1364)
  Docs/02-getting-started/quick-deploy-in-docker.md
  Docs/02-getting-started/quick-deployment/deploy-stonedb-with-deb.md
  Docs/02-getting-started/quick-deployment/deploy-stonedb-with-rpm.md
  Docs/02-getting-started/quick-deployment/quick-deployment-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deploy-in-docker.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/deploy-stonedb-with-deb.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/deploy-stonedb-with-rpm.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/quick-deployment-57.md
Labels: PR-docs

#1372 fix(tianm):oltp_read_write.lua sysbench returned error 1366(#1371)
  storage/tianmu/core/merge_operator.cpp
  storage/tianmu/util/bitset.h
Labels: PR-bug

#1377 feat(index): Failed to insert a null value to the composite primary key. #1374
  mysql-test/suite/tianmu/r/composite_primary_key.result
  mysql-test/suite/tianmu/t/composite_primary_key.test
  storage/tianmu/index/rdb_meta_manager.cpp
Labels: PR-feature

#1378 fix(workflow): rm no longer use testcase issue410 and make issue1111 …
  mysql-test/suite/tianmu/r/issue410.result
  mysql-test/suite/tianmu/t/issue1111.testbak
  mysql-test/suite/tianmu/t/issue410.testbak
Labels: PR-bug

#1355 fix(tianmu): Avoid OOM when data too large and aggregated (#949)
  scripts/my.cnf.sample
  storage/tianmu/core/aggregation_algorithm.cpp
  storage/tianmu/core/aggregation_algorithm.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/engine.h
  storage/tianmu/handler/ha_tianmu.cpp
  storage/tianmu/mm/huge_heap_policy.cpp
  storage/tianmu/mm/memory_block.h
  storage/tianmu/mm/memory_handling_policy.cpp
  storage/tianmu/mm/memory_statistics.cpp
  storage/tianmu/mm/memory_statistics.h
  storage/tianmu/system/configuration.cpp
  storage/tianmu/system/configuration.h
Labels: PR-bug

#1390 fix(core): fix the text field in subquery does no…
  mysql-test/suite/tianmu/r/issue1385.result
  mysql-test/suite/tianmu/t/issue1385.test
  storage/tianmu/core/query.cpp
Labels: PR-bug

#1392 fix(tianmu):set sql_mode=NO_KEY_ERROR,Cannot create stored routine xxx. Check warnings(#1388)
  mysql-test/suite/tianmu/r/issue1065.result
  mysql-test/suite/tianmu/t/issue1065.test
  scripts/mysql_system_tables.sql
  scripts/mysql_system_tables_fix.sql
Labels: PR-bug

#1451 docs(stonedb): Update the latest docs(#1450)
  Docs/02-getting-started/quick-deployment-of-stonedb-as-the-secondary-database.md
  Docs/02-getting-started/quick-deployment/deploy-stonedb-with-rpm.md
  Docs/02-getting-started/quick-deployment/deploy-stonedb-with-tar.md
  Docs/02-getting-started/quick-deployment/quick-deployment-57.md
  Docs/release-notes.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment-of-stonedb-as-the-secondary-database.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/deploy-stonedb-with-deb.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/deploy-stonedb-with-rpm.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/deploy-stonedb-with-tar.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment/quick-deployment-57.md
  website/i18n/zh/docusaurus-plugin-content-docs/current/release-notes.md
Labels: PR-docs

#1459 fix(mtr):Resolve the nightly run error problem(#1458)
  mysql-test/suite/tianmu/r/issue1111.result
  mysql-test/suite/tianmu/r/issue1174.result
  mysql-test/suite/tianmu/t/issue1111-slave.opt
  mysql-test/suite/tianmu/t/issue1111.test
  mysql-test/suite/tianmu/t/issue1174-slave.opt
  mysql-test/suite/tianmu/t/issue1174.test
Labels: PR-bug

#1396 fix(workflow): fix can not run lcov in workflow
  .github/workflows/pull_requests.yml
Labels: PR-bug

#1447 feat(.git): addd ignore scripts in git ignore file 1406
  .gitignore
Labels: PR-feature

#1463 fix(core): backport fix the bug of incorrect result set of count function #1440
  mysql-test/suite/tianmu/r/issue736.result
  mysql-test/suite/tianmu/t/issue736.test
  storage/tianmu/core/group_distinct_table.cpp
Labels: PR-bug

#1469 fix(tianmu):(Primary/Secondary)Error 1032 occasionally occurs during …
  mysql-test/suite/tianmu/r/issue1325.result
  mysql-test/suite/tianmu/r/issue1464.result
  mysql-test/suite/tianmu/t/issue1325.test
  mysql-test/suite/tianmu/t/issue1464-slave.opt
  mysql-test/suite/tianmu/t/issue1464.test
  storage/tianmu/handler/ha_tianmu.cpp
Labels: PR-bug

#1471 test(mtr): add integer/unsigned/in subquery/create temporary testcases and update escape.test(#1196)
  mysql-test/suite/tianmu/r/bigint_unsigned.result
  mysql-test/suite/tianmu/r/create_tmp.result
  mysql-test/suite/tianmu/r/escape.result
  mysql-test/suite/tianmu/r/in_withpk.result
  mysql-test/suite/tianmu/r/integer_range.result
  mysql-test/suite/tianmu/t/bigint_unsigned.test
  mysql-test/suite/tianmu/t/create_tmp.test
  mysql-test/suite/tianmu/t/escape.test
  mysql-test/suite/tianmu/t/in_withpk.test
  mysql-test/suite/tianmu/t/integer_range.test
Labels: PR-testing

#1455 feat(tianmu): backport delete, phase 1, fetch rename variable changes in commit 50865ef #702
  storage/tianmu/core/column_share.cpp
  storage/tianmu/core/column_share.h
  storage/tianmu/core/dpn.h
  storage/tianmu/core/pack.cpp
  storage/tianmu/core/pack.h
  storage/tianmu/core/pack_int.cpp
  storage/tianmu/core/pack_int.h
  storage/tianmu/core/pack_str.cpp
  storage/tianmu/core/pack_str.h
  storage/tianmu/core/rc_attr.cpp
  storage/tianmu/core/rc_attr.h
  storage/tianmu/core/rcattr_exeq_rs.cpp
  storage/tianmu/core/rcattr_exqp.cpp
  storage/tianmu/core/rsi_bloom.cpp
  storage/tianmu/core/rsi_cmap.cpp
  storage/tianmu/core/rsi_histogram.cpp
Labels: PR-feature

#1461 fix(load): instance crashed while loading data (#1421)
  storage/tianmu/common/common_definitions.h
  storage/tianmu/core/engine.cpp
  storage/tianmu/core/rc_attr.cpp
  storage/tianmu/core/rc_table.cpp
  storage/tianmu/core/transaction.h
Labels: PR-bug

#1504 test(mtr): Optimize parallel scheduling to execute more innodb engine testcases, add date type and std func testcase(#1196)
  .github/workflows/pull_requests.yml
  mysql-test/suite/innodb/include/innodb_testlist
  mysql-test/suite/tianmu/r/date_formats.result
  mysql-test/suite/tianmu/r/std_test.result
  mysql-test/suite/tianmu/std_data/tinyint_range.tbl
  mysql-test/suite/tianmu/t/date_formats.test
  mysql-test/suite/tianmu/t/std_test.test
Labels: PR-testing

#1506 fix(tianmu): fix crash when the aggregated element was decimal (#1402)
  mysql-test/suite/tianmu/r/issue1402.result
  mysql-test/suite/tianmu/t/issue1402.test
  sql/item.h
  storage/tianmu/core/aggregation_algorithm.cpp
  storage/tianmu/core/item_tianmu_field.cpp
  storage/tianmu/core/item_tianmu_field.h
  storage/tianmu/core/pack_guardian.cpp
Labels: PR-bug
